// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSach.database;

#nullable disable

namespace QLSach.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241113080226_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("liked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<bool>("saved")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookInteractions");
                });

            modelBuilder.Entity("QLSach.database.models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("create_at")
                        .HasColumnType("date");

                    b.Property<DateOnly>("update_at")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eaque sit minus magnam. Temporibus dolore non fuga quasi sit doloremque sit. Id hic pariatur qui autem.",
                            Name = "voluptatem",
                            create_at = new DateOnly(2024, 11, 13),
                            update_at = new DateOnly(2024, 11, 13)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Voluptatem corporis eum sit eligendi. Sunt autem porro ipsam ex error eius ut vitae laboriosam. Non eum doloribus neque cum tempore enim laboriosam. Quasi eaque dicta officiis. Occaecati consequatur et tempora. Dolorem ea voluptates nostrum aut molestiae voluptatem.",
                            Name = "Numquam earum repellendus incidunt in ipsam.\nLibero quo odio alias harum repudiandae vel perferendis blanditiis.\nLaborum nesciunt quae alias voluptas blanditiis.",
                            create_at = new DateOnly(2024, 11, 13),
                            update_at = new DateOnly(2024, 11, 13)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dolor ut magni minima possimus soluta ad. Officiis voluptas ad architecto est laudantium nihil nobis. Ipsa at eligendi ad quia est sit. Omnis dignissimos velit placeat alias qui.",
                            Name = "Quasi blanditiis neque quia quis.\nLibero cum ad reprehenderit sed voluptatibus sed sit.\nVoluptas reiciendis vitae velit.\nSoluta at libero est voluptas necessitatibus quae.\nIure libero quos non soluta voluptatum non inventore id aut.",
                            create_at = new DateOnly(2024, 11, 13),
                            update_at = new DateOnly(2024, 11, 13)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Deserunt quidem eum est quas omnis. Esse reprehenderit ea omnis atque nam nihil est molestias vel. Illo voluptas ex deserunt reprehenderit dolores sapiente cumque mollitia.",
                            Name = "Neque itaque in. Sit et cumque voluptatem aperiam est incidunt ut et. Velit itaque beatae exercitationem qui ut alias deserunt repudiandae quae. Qui porro consequuntur ut ut et. Et dolor non maxime omnis quo dolores vel dolores quam. Ea et quod.",
                            create_at = new DateOnly(2024, 11, 13),
                            update_at = new DateOnly(2024, 11, 13)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Et a quam. Ab iusto est ab facere repellendus alias id consequatur. Beatae doloremque porro dolor dicta.",
                            Name = "et",
                            create_at = new DateOnly(2024, 11, 13),
                            update_at = new DateOnly(2024, 11, 13)
                        });
                });

            modelBuilder.Entity("QLSach.database.models.CategoryBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoriesBook");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 2,
                            BookId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 5,
                            BookId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            BookId = 25,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 7,
                            BookId = 28,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            BookId = 26,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 28,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            BookId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 11,
                            BookId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 12,
                            BookId = 15,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            BookId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 14,
                            BookId = 23,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 15,
                            BookId = 19,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            BookId = 24,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 17,
                            BookId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            BookId = 22,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            BookId = 16,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 20,
                            BookId = 16,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.HasIndex("parent_id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 6,
                            UserId = 14,
                            content = "Enim sint reprehenderit et dolores et fugit deleniti sed sequi."
                        },
                        new
                        {
                            Id = 2,
                            BookId = 13,
                            UserId = 16,
                            content = "Impedit iste aut ducimus quo est eius."
                        },
                        new
                        {
                            Id = 3,
                            BookId = 27,
                            UserId = 16,
                            content = "Expedita omnis quia sint beatae magni saepe et et."
                        },
                        new
                        {
                            Id = 4,
                            BookId = 3,
                            UserId = 16,
                            content = "Repellendus est a vel."
                        },
                        new
                        {
                            Id = 5,
                            BookId = 1,
                            UserId = 3,
                            content = "Rerum in nisi et ab."
                        },
                        new
                        {
                            Id = 6,
                            BookId = 23,
                            UserId = 1,
                            content = "Aut ipsam quod quidem accusantium."
                        },
                        new
                        {
                            Id = 7,
                            BookId = 19,
                            UserId = 13,
                            content = "Nulla itaque recusandae voluptas."
                        },
                        new
                        {
                            Id = 8,
                            BookId = 2,
                            UserId = 4,
                            content = "Quibusdam quasi omnis voluptatem porro."
                        },
                        new
                        {
                            Id = 9,
                            BookId = 8,
                            UserId = 3,
                            content = "Et ea rem quibusdam atque saepe."
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            UserId = 13,
                            content = "Officiis aut illum ut."
                        },
                        new
                        {
                            Id = 11,
                            BookId = 19,
                            UserId = 15,
                            content = "Voluptatem magni quisquam quas sit maiores et quia."
                        },
                        new
                        {
                            Id = 12,
                            BookId = 21,
                            UserId = 14,
                            content = "Et commodi ad in culpa voluptas ut non occaecati."
                        },
                        new
                        {
                            Id = 13,
                            BookId = 17,
                            UserId = 14,
                            content = "Omnis ut dolores et qui molestiae."
                        },
                        new
                        {
                            Id = 14,
                            BookId = 3,
                            UserId = 10,
                            content = "Sed quas occaecati deleniti incidunt aut quo dolores."
                        },
                        new
                        {
                            Id = 15,
                            BookId = 28,
                            UserId = 5,
                            content = "Dolor non qui expedita rerum sed dolorem iusto earum quam."
                        },
                        new
                        {
                            Id = 16,
                            BookId = 11,
                            UserId = 4,
                            content = "Sit animi itaque ea nam excepturi."
                        },
                        new
                        {
                            Id = 17,
                            BookId = 21,
                            UserId = 1,
                            content = "Dolor neque libero.",
                            parent_id = 2
                        },
                        new
                        {
                            Id = 18,
                            BookId = 10,
                            UserId = 3,
                            content = "Quia illum itaque quisquam dignissimos.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 19,
                            BookId = 8,
                            UserId = 15,
                            content = "Porro odit hic voluptate beatae omnis est necessitatibus iste quis.",
                            parent_id = 4
                        },
                        new
                        {
                            Id = 20,
                            BookId = 25,
                            UserId = 1,
                            content = "Amet id cupiditate molestias quos autem tempora et sed.",
                            parent_id = 5
                        },
                        new
                        {
                            Id = 21,
                            BookId = 28,
                            UserId = 4,
                            content = "Culpa non laboriosam.",
                            parent_id = 12
                        },
                        new
                        {
                            Id = 22,
                            BookId = 20,
                            UserId = 1,
                            content = "Quasi rem hic fuga ipsum delectus eius numquam placeat dolor.",
                            parent_id = 13
                        },
                        new
                        {
                            Id = 23,
                            BookId = 13,
                            UserId = 15,
                            content = "Officiis rerum reiciendis.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 24,
                            BookId = 7,
                            UserId = 2,
                            content = "Consequatur dolore non vero eos hic est rerum.",
                            parent_id = 9
                        },
                        new
                        {
                            Id = 25,
                            BookId = 23,
                            UserId = 5,
                            content = "Vitae repudiandae quae.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 26,
                            BookId = 8,
                            UserId = 4,
                            content = "Voluptatibus earum ipsam recusandae debitis unde.",
                            parent_id = 10
                        },
                        new
                        {
                            Id = 27,
                            BookId = 23,
                            UserId = 12,
                            content = "Ipsam qui tempore et harum delectus.",
                            parent_id = 10
                        },
                        new
                        {
                            Id = 28,
                            BookId = 24,
                            UserId = 8,
                            content = "Sit qui ducimus.",
                            parent_id = 5
                        },
                        new
                        {
                            Id = 29,
                            BookId = 14,
                            UserId = 5,
                            content = "Et facere dolorem est earum omnis tempore.",
                            parent_id = 13
                        },
                        new
                        {
                            Id = 30,
                            BookId = 9,
                            UserId = 1,
                            content = "Ex quis laboriosam facere ea labore inventore.",
                            parent_id = 9
                        },
                        new
                        {
                            Id = 31,
                            BookId = 20,
                            UserId = 11,
                            content = "Eaque est perspiciatis nostrum odit est aut dolor iusto reprehenderit.",
                            parent_id = 2
                        },
                        new
                        {
                            Id = 32,
                            BookId = 3,
                            UserId = 14,
                            content = "Magnam debitis deleniti omnis.",
                            parent_id = 3
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "voluptas"
                        },
                        new
                        {
                            id = 2,
                            name = "in"
                        },
                        new
                        {
                            id = 3,
                            name = "eveniet"
                        },
                        new
                        {
                            id = 4,
                            name = "temporibus"
                        },
                        new
                        {
                            id = 5,
                            name = "laboriosam"
                        },
                        new
                        {
                            id = 6,
                            name = "cumque"
                        },
                        new
                        {
                            id = 7,
                            name = "quos"
                        },
                        new
                        {
                            id = 8,
                            name = "eum"
                        },
                        new
                        {
                            id = 9,
                            name = "labore"
                        },
                        new
                        {
                            id = 10,
                            name = "minima"
                        },
                        new
                        {
                            id = 11,
                            name = "eaque"
                        },
                        new
                        {
                            id = 12,
                            name = "et"
                        },
                        new
                        {
                            id = 13,
                            name = "voluptates"
                        },
                        new
                        {
                            id = 14,
                            name = "doloribus"
                        },
                        new
                        {
                            id = 15,
                            name = "rerum"
                        },
                        new
                        {
                            id = 16,
                            name = "dolor"
                        },
                        new
                        {
                            id = 17,
                            name = "et"
                        },
                        new
                        {
                            id = 18,
                            name = "aliquam"
                        },
                        new
                        {
                            id = 19,
                            name = "dolor"
                        },
                        new
                        {
                            id = 20,
                            name = "omnis"
                        },
                        new
                        {
                            id = 21,
                            name = "temporibus"
                        },
                        new
                        {
                            id = 22,
                            name = "assumenda"
                        },
                        new
                        {
                            id = 23,
                            name = "quas"
                        },
                        new
                        {
                            id = 24,
                            name = "voluptas"
                        },
                        new
                        {
                            id = 25,
                            name = "in"
                        },
                        new
                        {
                            id = 26,
                            name = "in"
                        },
                        new
                        {
                            id = 27,
                            name = "quia"
                        },
                        new
                        {
                            id = 28,
                            name = "aperiam"
                        },
                        new
                        {
                            id = 29,
                            name = "repudiandae"
                        },
                        new
                        {
                            id = 30,
                            name = "dolor"
                        },
                        new
                        {
                            id = 31,
                            name = "officiis"
                        },
                        new
                        {
                            id = 32,
                            name = "assumenda"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("book_id")
                        .IsUnique();

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            book_id = 22,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 2,
                            book_id = 9,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 3,
                            book_id = 8,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 4,
                            book_id = 6,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 5,
                            book_id = 5,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 6,
                            book_id = 9,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 7,
                            book_id = 5,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 8,
                            book_id = 4,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 9,
                            book_id = 2,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 10,
                            book_id = 6,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 11,
                            book_id = 28,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 12,
                            book_id = 2,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 13,
                            book_id = 8,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 14,
                            book_id = 9,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 15,
                            book_id = 9,
                            path = ".\\resources\\images\\poster.png"
                        },
                        new
                        {
                            Id = 16,
                            book_id = 8,
                            path = ".\\resources\\images\\poster.png"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("borrow_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expected_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("register_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("return_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Register");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 14,
                            Status = "Borrowed",
                            UserId = 11,
                            borrow_at = new DateTime(2024, 11, 12, 5, 25, 40, 861, DateTimeKind.Local).AddTicks(4714),
                            expected_at = new DateTime(2024, 11, 14, 11, 28, 12, 411, DateTimeKind.Local).AddTicks(1146),
                            register_at = new DateTime(2024, 11, 7, 11, 28, 12, 411, DateTimeKind.Local).AddTicks(1146)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 21,
                            Status = "Completed",
                            UserId = 15,
                            borrow_at = new DateTime(2024, 11, 8, 0, 0, 59, 388, DateTimeKind.Local).AddTicks(9467),
                            expected_at = new DateTime(2024, 11, 18, 13, 23, 13, 885, DateTimeKind.Local).AddTicks(6917),
                            register_at = new DateTime(2024, 11, 11, 13, 23, 13, 885, DateTimeKind.Local).AddTicks(6917),
                            return_at = new DateTime(2024, 11, 11, 21, 46, 35, 391, DateTimeKind.Local).AddTicks(845)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 7,
                            Status = "Completed",
                            UserId = 7,
                            borrow_at = new DateTime(2024, 11, 10, 21, 50, 42, 373, DateTimeKind.Local).AddTicks(5091),
                            expected_at = new DateTime(2024, 11, 19, 17, 18, 37, 572, DateTimeKind.Local).AddTicks(3173),
                            register_at = new DateTime(2024, 11, 12, 17, 18, 37, 572, DateTimeKind.Local).AddTicks(3173),
                            return_at = new DateTime(2024, 11, 13, 5, 37, 14, 472, DateTimeKind.Local).AddTicks(8820)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 10,
                            Status = "Pending",
                            UserId = 1,
                            expected_at = new DateTime(2024, 11, 14, 1, 51, 54, 495, DateTimeKind.Local).AddTicks(9683),
                            register_at = new DateTime(2024, 11, 7, 1, 51, 54, 495, DateTimeKind.Local).AddTicks(9683)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 1,
                            Status = "Borrowed",
                            UserId = 3,
                            borrow_at = new DateTime(2024, 11, 12, 18, 38, 42, 246, DateTimeKind.Local).AddTicks(1090),
                            expected_at = new DateTime(2024, 11, 18, 21, 21, 53, 953, DateTimeKind.Local).AddTicks(5164),
                            register_at = new DateTime(2024, 11, 11, 21, 21, 53, 953, DateTimeKind.Local).AddTicks(5164)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 23,
                            Status = "Borrowed",
                            UserId = 7,
                            borrow_at = new DateTime(2024, 11, 8, 16, 52, 12, 868, DateTimeKind.Local).AddTicks(9167),
                            expected_at = new DateTime(2024, 11, 15, 1, 56, 3, 898, DateTimeKind.Local).AddTicks(3723),
                            register_at = new DateTime(2024, 11, 8, 1, 56, 3, 898, DateTimeKind.Local).AddTicks(3723)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 6,
                            Status = "Canceled",
                            UserId = 7,
                            register_at = new DateTime(2024, 11, 6, 20, 39, 37, 96, DateTimeKind.Local).AddTicks(4873)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 17,
                            Status = "Pending",
                            UserId = 2,
                            expected_at = new DateTime(2024, 11, 18, 7, 8, 52, 809, DateTimeKind.Local).AddTicks(9156),
                            register_at = new DateTime(2024, 11, 11, 7, 8, 52, 809, DateTimeKind.Local).AddTicks(9156)
                        },
                        new
                        {
                            Id = 9,
                            BookId = 25,
                            Status = "Pending",
                            UserId = 5,
                            expected_at = new DateTime(2024, 11, 18, 19, 20, 18, 831, DateTimeKind.Local).AddTicks(8567),
                            register_at = new DateTime(2024, 11, 11, 19, 20, 18, 831, DateTimeKind.Local).AddTicks(8567)
                        },
                        new
                        {
                            Id = 10,
                            BookId = 6,
                            Status = "Canceled",
                            UserId = 6,
                            register_at = new DateTime(2024, 11, 8, 1, 13, 33, 209, DateTimeKind.Local).AddTicks(3089)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 12,
                            Status = "Borrowed",
                            UserId = 9,
                            borrow_at = new DateTime(2024, 11, 9, 8, 9, 52, 723, DateTimeKind.Local).AddTicks(4179),
                            expected_at = new DateTime(2024, 11, 15, 10, 15, 3, 418, DateTimeKind.Local).AddTicks(6726),
                            register_at = new DateTime(2024, 11, 8, 10, 15, 3, 418, DateTimeKind.Local).AddTicks(6726)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 19,
                            Status = "Borrowed",
                            UserId = 9,
                            borrow_at = new DateTime(2024, 11, 10, 20, 7, 2, 682, DateTimeKind.Local).AddTicks(1833),
                            expected_at = new DateTime(2024, 11, 19, 11, 4, 4, 830, DateTimeKind.Local).AddTicks(9433),
                            register_at = new DateTime(2024, 11, 12, 11, 4, 4, 830, DateTimeKind.Local).AddTicks(9433)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 3,
                            Status = "Borrowed",
                            UserId = 11,
                            borrow_at = new DateTime(2024, 11, 11, 11, 0, 20, 648, DateTimeKind.Local).AddTicks(848),
                            expected_at = new DateTime(2024, 11, 16, 18, 41, 56, 185, DateTimeKind.Local).AddTicks(1143),
                            register_at = new DateTime(2024, 11, 9, 18, 41, 56, 185, DateTimeKind.Local).AddTicks(1143)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 16,
                            Status = "Canceled",
                            UserId = 12,
                            register_at = new DateTime(2024, 11, 8, 0, 10, 23, 761, DateTimeKind.Local).AddTicks(7069)
                        },
                        new
                        {
                            Id = 15,
                            BookId = 6,
                            Status = "Borrowed",
                            UserId = 14,
                            borrow_at = new DateTime(2024, 11, 7, 17, 5, 11, 139, DateTimeKind.Local).AddTicks(4931),
                            expected_at = new DateTime(2024, 11, 20, 10, 27, 22, 630, DateTimeKind.Local).AddTicks(2481),
                            register_at = new DateTime(2024, 11, 13, 10, 27, 22, 630, DateTimeKind.Local).AddTicks(2481)
                        },
                        new
                        {
                            Id = 16,
                            BookId = 28,
                            Status = "Borrowed",
                            UserId = 3,
                            borrow_at = new DateTime(2024, 11, 9, 15, 48, 27, 230, DateTimeKind.Local).AddTicks(5825),
                            expected_at = new DateTime(2024, 11, 15, 1, 37, 28, 305, DateTimeKind.Local).AddTicks(1499),
                            register_at = new DateTime(2024, 11, 8, 1, 37, 28, 305, DateTimeKind.Local).AddTicks(1499)
                        });
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "animi",
                            UserName = "Oda Greenholt"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Magnam molestiae suscipit similique fuga dignissimos et necessitatibus et. Sit id fuga consectetur in repudiandae. Est dolor tenetur sequi dignissimos.",
                            UserName = "Justus Feil"
                        },
                        new
                        {
                            Id = 3,
                            Password = "dignissimos",
                            UserName = "Brendan Welch"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Quos omnis esse.",
                            UserName = "Britney Purdy"
                        },
                        new
                        {
                            Id = 5,
                            Password = "Nemo voluptatum modi tempora. Perferendis in similique cupiditate voluptatem quia exercitationem eos quisquam. Voluptatibus sunt ut aperiam nulla enim eos culpa tempore incidunt. Vero amet sit nisi qui qui autem asperiores et adipisci. Sit sed autem est saepe.",
                            UserName = "Marcia Langworth"
                        },
                        new
                        {
                            Id = 6,
                            Password = "Repellat rerum animi beatae.",
                            UserName = "Luciano Nikolaus"
                        },
                        new
                        {
                            Id = 7,
                            Password = "Enim quasi ex veritatis.",
                            UserName = "Elsa Swaniawski"
                        },
                        new
                        {
                            Id = 8,
                            Password = "eum",
                            UserName = "Llewellyn Bartoletti"
                        },
                        new
                        {
                            Id = 9,
                            Password = "Vel minus ut nam voluptate blanditiis sit. Natus sint suscipit repellendus molestiae voluptatem corrupti eaque fugiat. Placeat a aut voluptas earum sunt dolorem commodi adipisci. Dolore et tempore ut sunt quia dolor autem ab.",
                            UserName = "Meredith Spinka"
                        },
                        new
                        {
                            Id = 10,
                            Password = "nemo",
                            UserName = "Travis Ortiz"
                        },
                        new
                        {
                            Id = 11,
                            Password = "Eaque quaerat expedita.",
                            UserName = "Adeline Kassulke"
                        },
                        new
                        {
                            Id = 12,
                            Password = "sit",
                            UserName = "Orval Considine"
                        },
                        new
                        {
                            Id = 13,
                            Password = "Ab numquam est magni.\nArchitecto accusantium est voluptatem.\nAut rem sed at.\nOccaecati perferendis qui dicta non.\nPlaceat voluptas aliquid amet.",
                            UserName = "Royal Howell"
                        },
                        new
                        {
                            Id = 14,
                            Password = "Omnis ut quia neque esse hic eligendi repudiandae vel.",
                            UserName = "Glennie Hamill"
                        },
                        new
                        {
                            Id = 15,
                            Password = "Tempore eligendi dignissimos optio.",
                            UserName = "Norberto Walker"
                        },
                        new
                        {
                            Id = 16,
                            Password = "Fugiat ut impedit voluptatem et voluptatem.",
                            UserName = "Deangelo Robel"
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("genre_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("quantity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("remaining")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("year_public")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("author_id")
                        .IsUnique();

                    b.HasIndex("genre_id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            author_id = 5,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(3024),
                            description = "Voluptas rerum ut ut officiis modi ut doloribus. Accusamus labore officiis. Consequatur delectus quae est illum doloremque. Amet commodi qui delectus assumenda aut. Et dicta dolorem fuga aut velit nihil quo nesciunt.",
                            genre_id = 28,
                            name = "At sed et sequi.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(3510),
                            views = 0,
                            year_public = 1912
                        },
                        new
                        {
                            Id = 2,
                            author_id = 28,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(4612),
                            description = "A nostrum aut sed. Odit perspiciatis dolor numquam itaque corporis perspiciatis provident voluptatem cumque. A architecto voluptatem officia aliquam placeat placeat veritatis quaerat. Aliquid occaecati asperiores eveniet quisquam quae tenetur sed consequuntur. Sunt et est ea aliquam.",
                            genre_id = 13,
                            name = "Vel quam itaque saepe voluptas facilis.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(4809),
                            views = 0,
                            year_public = 1994
                        },
                        new
                        {
                            Id = 3,
                            author_id = 30,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(4822),
                            description = "Optio consequuntur excepturi qui. Nisi quam alias sit qui voluptatibus error quos. Sed magni est officia velit ab et quia. Quis adipisci quo culpa sunt quo repudiandae ut totam officiis.",
                            genre_id = 9,
                            name = "Soluta doloribus consequatur et et nisi quae.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(4926),
                            views = 0,
                            year_public = 1944
                        },
                        new
                        {
                            Id = 4,
                            author_id = 28,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(4939),
                            description = "Harum consectetur dolorum veritatis veritatis deleniti delectus. Non qui est eum sit repudiandae sunt dolorem quo autem. Ut eligendi aut rerum aut. Culpa earum sit dolorem soluta voluptate asperiores.",
                            genre_id = 26,
                            name = "Aliquid quas hic molestiae et sit ut expedita suscipit sit.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5036),
                            views = 0,
                            year_public = 1953
                        },
                        new
                        {
                            Id = 5,
                            author_id = 14,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5047),
                            description = "Consequatur nobis non doloribus eaque cumque saepe ea. Ea temporibus laboriosam. Et iusto tempora sed a ut et architecto. Atque impedit sed corrupti tenetur voluptatem autem ea.",
                            genre_id = 5,
                            name = "Nobis occaecati facere est.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5134),
                            views = 0,
                            year_public = 1992
                        },
                        new
                        {
                            Id = 6,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5145),
                            description = "Qui suscipit placeat suscipit iure ut ducimus suscipit consequatur. Suscipit unde doloribus quia dolorum quia voluptatibus ratione. Harum repellendus quia. Non ut dolor ea recusandae blanditiis et.",
                            genre_id = 27,
                            name = "Dolores beatae temporibus asperiores quo sit ea.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5238),
                            views = 0,
                            year_public = 1978
                        },
                        new
                        {
                            Id = 7,
                            author_id = 30,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5248),
                            description = "Rerum labore tempora deleniti fugiat tempora. Quia aut officia delectus fuga officiis excepturi. Nostrum earum nesciunt aut odit modi. Suscipit aut occaecati. Quia quia accusamus quod. Temporibus dolore sapiente assumenda officia.",
                            genre_id = 14,
                            name = "Non dolore nobis unde iure in iure et iure.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5342),
                            views = 0,
                            year_public = 1949
                        },
                        new
                        {
                            Id = 8,
                            author_id = 32,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5357),
                            description = "Ex hic quia labore placeat similique. Pariatur doloribus minima amet veritatis placeat voluptatem. Inventore labore atque quos minima non qui rerum ut.",
                            genre_id = 23,
                            name = "Voluptatem et repellat itaque facere sed id omnis.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5432),
                            views = 0,
                            year_public = 1990
                        },
                        new
                        {
                            Id = 9,
                            author_id = 23,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5442),
                            description = "Sunt pariatur enim voluptatem ullam. Sit non numquam qui atque repudiandae voluptatem. Temporibus explicabo ullam labore.",
                            genre_id = 18,
                            name = "Dolore enim voluptatem minima ea facere.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5509),
                            views = 0,
                            year_public = 1996
                        },
                        new
                        {
                            Id = 10,
                            author_id = 12,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5519),
                            description = "Tempore ipsa nostrum sit hic. Recusandae consequatur veniam dolore est molestiae hic excepturi. Deleniti est illum illum autem neque autem dignissimos quia. Ut omnis quisquam labore facilis velit sapiente dolor qui natus. Rerum officiis est voluptatem accusantium quos labore eius.",
                            genre_id = 31,
                            name = "Dolorem velit non eius id neque accusantium deserunt.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5630),
                            views = 0,
                            year_public = 1957
                        },
                        new
                        {
                            Id = 11,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5641),
                            description = "Nesciunt mollitia hic laudantium ex totam. Animi ipsum rem porro maxime dolores quasi. Qui officia distinctio sunt. Rerum at expedita nemo temporibus.",
                            genre_id = 23,
                            name = "Illum nesciunt in sapiente porro numquam quisquam fugit ea.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5720),
                            views = 0,
                            year_public = 1988
                        },
                        new
                        {
                            Id = 12,
                            author_id = 10,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5731),
                            description = "Qui ad voluptatum quo cumque omnis. Nulla voluptas non iure esse sit dolor eius enim. Vel repellat sit voluptas voluptatum sapiente in et. Explicabo possimus quia labore voluptate autem expedita. Omnis corporis ipsam ullam aut. Adipisci iste est in.",
                            genre_id = 6,
                            name = "Nemo est ad laudantium iste vero quos.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5844),
                            views = 0,
                            year_public = 1960
                        },
                        new
                        {
                            Id = 13,
                            author_id = 17,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5854),
                            description = "Debitis nihil voluptas aperiam voluptatem voluptatibus placeat. Dolor sed aspernatur consequuntur. Voluptatem quidem laborum porro modi et. Ipsum iure officia expedita qui.",
                            genre_id = 21,
                            name = "Provident quibusdam illo quibusdam in sed.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5936),
                            views = 0,
                            year_public = 2000
                        },
                        new
                        {
                            Id = 14,
                            author_id = 1,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(5946),
                            description = "Ea rerum assumenda autem ut enim. Quisquam assumenda eius et ut odio magni laborum et. Ipsa et quod ea animi hic sunt totam molestiae voluptatem. Omnis quis doloremque architecto. Aspernatur nostrum sit aliquid dignissimos dolor nemo nemo laborum.",
                            genre_id = 32,
                            name = "Quisquam fugiat aut id.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6050),
                            views = 0,
                            year_public = 1931
                        },
                        new
                        {
                            Id = 15,
                            author_id = 12,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6060),
                            description = "Eaque illo aut non ea ullam voluptas odit quas. Numquam est sit vel quia qui molestiae dolorem. Et cumque delectus dolorum. Non similique voluptatem dolores. Ducimus quasi quia iure.",
                            genre_id = 6,
                            name = "Impedit sequi repellendus officia corporis aut perferendis molestiae voluptatem.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6153),
                            views = 0,
                            year_public = 1902
                        },
                        new
                        {
                            Id = 16,
                            author_id = 8,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6163),
                            description = "Qui esse illum dolores. Ullam ea expedita rerum eos adipisci non nesciunt commodi minima. Modi deserunt ut id voluptate dolores.",
                            genre_id = 25,
                            name = "Tenetur similique qui dolore sit itaque.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6236),
                            views = 0,
                            year_public = 1990
                        },
                        new
                        {
                            Id = 17,
                            author_id = 23,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6247),
                            description = "Temporibus sit et voluptatem excepturi vel enim est molestiae. Cumque quaerat non neque facilis at hic qui harum. Unde tenetur illum. Totam possimus ea nesciunt ipsum totam culpa id. Consectetur delectus reiciendis optio.",
                            genre_id = 12,
                            name = "Corporis velit sed.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6341),
                            views = 0,
                            year_public = 1952
                        },
                        new
                        {
                            Id = 18,
                            author_id = 13,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6352),
                            description = "Sed quia quibusdam placeat natus quaerat consequatur. Rerum repudiandae officiis qui quia quia dicta ut qui nihil. Illum in qui neque.",
                            genre_id = 14,
                            name = "Ea qui tenetur excepturi consequuntur tenetur dicta.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6425),
                            views = 0,
                            year_public = 2019
                        },
                        new
                        {
                            Id = 19,
                            author_id = 29,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6436),
                            description = "Sunt excepturi inventore omnis. Repellendus ut tempore cupiditate consequatur. Nisi est dignissimos accusamus architecto corporis quasi. Modi molestiae alias quod sit ea. Iusto vel alias aut aut atque rerum recusandae. Quia voluptas eligendi harum qui accusantium vero molestias.",
                            genre_id = 14,
                            name = "Ex nemo voluptatem.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6542),
                            views = 0,
                            year_public = 1915
                        },
                        new
                        {
                            Id = 20,
                            author_id = 21,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6553),
                            description = "Ut maiores aliquid quo accusantium cupiditate sapiente. Eaque voluptas aspernatur quam id dignissimos molestias ad. Quam porro facere sit aut minima officia. Pariatur laborum laboriosam voluptatem reiciendis omnis repudiandae rerum.",
                            genre_id = 16,
                            name = "Earum minus ut et ipsa a.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6646),
                            views = 0,
                            year_public = 1983
                        },
                        new
                        {
                            Id = 21,
                            author_id = 14,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6657),
                            description = "Error corporis ex omnis architecto. Nihil voluptates voluptatem voluptas voluptatum rem ut. Placeat unde eligendi ut rem magnam. Modi ipsam quis beatae possimus eum ea consequatur voluptatem quos.",
                            genre_id = 22,
                            name = "Odio et dolores.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6736),
                            views = 0,
                            year_public = 1904
                        },
                        new
                        {
                            Id = 22,
                            author_id = 4,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6747),
                            description = "Consequatur quo illum esse optio aut nam mollitia repellendus accusantium. Voluptatem qui labore magni. Qui minus ducimus. Est culpa odio quia ea enim ut totam. Aut numquam aspernatur enim deserunt iure corporis ut est illo.",
                            genre_id = 16,
                            name = "Non nam natus alias dolorum hic ex reprehenderit.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6849),
                            views = 0,
                            year_public = 1980
                        },
                        new
                        {
                            Id = 23,
                            author_id = 30,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6860),
                            description = "Placeat voluptatem nisi ut qui maiores facere voluptate voluptas. Commodi fuga ut eum et veniam tempore dolor assumenda. Animi laborum fugit tempora et illo sunt eius. Earum sed molestiae ducimus. Voluptates quia nostrum natus et in in sint harum. Autem tempora esse dolores similique autem rerum et.",
                            genre_id = 5,
                            name = "Corrupti non et quia ut excepturi.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6982),
                            views = 0,
                            year_public = 1984
                        },
                        new
                        {
                            Id = 24,
                            author_id = 22,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(6993),
                            description = "Aut doloribus fuga dolorem adipisci et sit vel. Magni cum architecto ea eius explicabo accusamus ipsum nobis. Qui fugit explicabo et eaque aliquid maxime qui ea.",
                            genre_id = 24,
                            name = "Et maxime consequatur iusto dolorem animi nisi quia omnis rem.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7200),
                            views = 0,
                            year_public = 1945
                        },
                        new
                        {
                            Id = 25,
                            author_id = 8,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7212),
                            description = "Eveniet omnis et nam. Excepturi nesciunt beatae et distinctio. Et harum id nihil qui ut magnam quo autem et. Iste dolorem autem expedita et repudiandae reprehenderit dicta delectus.",
                            genre_id = 13,
                            name = "Est possimus et eius perferendis voluptas debitis aut et tempora.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7306),
                            views = 0,
                            year_public = 1941
                        },
                        new
                        {
                            Id = 26,
                            author_id = 8,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7317),
                            description = "Quaerat labore quia dolorem laboriosam velit debitis. Totam maiores est voluptates. Maiores quod dolores rerum magnam dolor facere sequi at. Vitae odit maiores consequuntur saepe architecto. Voluptas nihil necessitatibus error vero veniam sequi non est nihil.",
                            genre_id = 25,
                            name = "Quo dolor ut eum tempora.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7415),
                            views = 0,
                            year_public = 1916
                        },
                        new
                        {
                            Id = 27,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7425),
                            description = "Natus non repudiandae rerum modi consectetur libero tempore eos. Praesentium vel sunt. Cumque beatae at minus autem omnis sint.",
                            genre_id = 28,
                            name = "Architecto sunt debitis atque.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7493),
                            views = 0,
                            year_public = 2003
                        },
                        new
                        {
                            Id = 28,
                            author_id = 27,
                            created_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7504),
                            description = "Quidem dolores vel reiciendis in fugit. Quia fugiat aperiam suscipit quia. Pariatur nisi hic natus aut accusantium totam qui.",
                            genre_id = 31,
                            name = "Ipsam cumque perferendis magni sit vel corrupti est ut.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 13, 15, 2, 26, 85, DateTimeKind.Local).AddTicks(7575),
                            views = 0,
                            year_public = 1902
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Possimus aliquid ipsum ut nulla recusandae.",
                            name = "Harold"
                        },
                        new
                        {
                            Id = 2,
                            description = "Repellendus alias rerum quod velit neque est assumenda tenetur corrupti.",
                            name = "Fidel"
                        },
                        new
                        {
                            Id = 3,
                            description = "Rem et iure qui deserunt adipisci asperiores atque.",
                            name = "Nelle"
                        },
                        new
                        {
                            Id = 4,
                            description = "Consequatur vel dolores praesentium corrupti.",
                            name = "Verdie"
                        },
                        new
                        {
                            Id = 5,
                            description = "Veniam optio ab laboriosam temporibus.",
                            name = "Vincent"
                        },
                        new
                        {
                            Id = 6,
                            description = "Vero quis explicabo nobis et.",
                            name = "Betsy"
                        },
                        new
                        {
                            Id = 7,
                            description = "Et harum voluptatum dicta et suscipit corporis architecto.",
                            name = "Antone"
                        },
                        new
                        {
                            Id = 8,
                            description = "Magni assumenda nihil est autem quo quis modi tenetur.",
                            name = "Nick"
                        },
                        new
                        {
                            Id = 9,
                            description = "Soluta enim rem ea.",
                            name = "Earl"
                        },
                        new
                        {
                            Id = 10,
                            description = "Animi dolore exercitationem eveniet dolorem illo nam.",
                            name = "Gerald"
                        },
                        new
                        {
                            Id = 11,
                            description = "Amet dicta eos qui.",
                            name = "Lila"
                        },
                        new
                        {
                            Id = 12,
                            description = "Aliquam sunt aut voluptas.",
                            name = "Melany"
                        },
                        new
                        {
                            Id = 13,
                            description = "Voluptates perferendis non eaque voluptate deleniti.",
                            name = "Laurence"
                        },
                        new
                        {
                            Id = 14,
                            description = "Et doloremque repellendus rem vero non recusandae omnis sunt laborum.",
                            name = "Donny"
                        },
                        new
                        {
                            Id = 15,
                            description = "Reprehenderit hic sequi minus aperiam quo.",
                            name = "Shaina"
                        },
                        new
                        {
                            Id = 16,
                            description = "Nemo nemo velit laudantium suscipit.",
                            name = "Bridie"
                        },
                        new
                        {
                            Id = 17,
                            description = "Dignissimos quibusdam omnis dignissimos occaecati consequatur labore ad iure.",
                            name = "Kimberly"
                        },
                        new
                        {
                            Id = 18,
                            description = "Voluptatum esse harum quibusdam porro.",
                            name = "Russ"
                        },
                        new
                        {
                            Id = 19,
                            description = "Ratione quae adipisci assumenda.",
                            name = "Jermey"
                        },
                        new
                        {
                            Id = 20,
                            description = "Cumque libero nihil ex.",
                            name = "Bettie"
                        },
                        new
                        {
                            Id = 21,
                            description = "Provident dignissimos placeat repellat molestiae eveniet repudiandae et.",
                            name = "Dariana"
                        },
                        new
                        {
                            Id = 22,
                            description = "Quam rem eligendi voluptas.",
                            name = "Tabitha"
                        },
                        new
                        {
                            Id = 23,
                            description = "Blanditiis et ut veniam.",
                            name = "Lacey"
                        },
                        new
                        {
                            Id = 24,
                            description = "Debitis quas veritatis et voluptatem itaque velit tenetur inventore.",
                            name = "Forrest"
                        },
                        new
                        {
                            Id = 25,
                            description = "Neque quasi soluta fuga quaerat.",
                            name = "Darian"
                        },
                        new
                        {
                            Id = 26,
                            description = "Et quia adipisci est et voluptatibus ipsam asperiores sed.",
                            name = "Joanne"
                        },
                        new
                        {
                            Id = 27,
                            description = "Quasi illum distinctio provident sunt quisquam sit aut rerum.",
                            name = "Dakota"
                        },
                        new
                        {
                            Id = 28,
                            description = "Facere architecto est vel.",
                            name = "Blaze"
                        },
                        new
                        {
                            Id = 29,
                            description = "Maxime et et fugit.",
                            name = "Trenton"
                        },
                        new
                        {
                            Id = 30,
                            description = "Aut qui adipisci officia saepe fuga iste impedit.",
                            name = "Lewis"
                        },
                        new
                        {
                            Id = 31,
                            description = "Voluptas beatae nesciunt corporis eos deleniti blanditiis.",
                            name = "Cicero"
                        },
                        new
                        {
                            Id = 32,
                            description = "Facilis pariatur blanditiis exercitationem.",
                            name = "Richmond"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "comment")
                        .WithOne("bookInteraction")
                        .HasForeignKey("QLSach.database.models.BookInteraction", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment");
                });

            modelBuilder.Entity("QLSach.database.models.CategoryBook", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "parent")
                        .WithMany("childrents")
                        .HasForeignKey("parent_id");

                    b.Navigation("book");

                    b.Navigation("parent");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "Book")
                        .WithOne("photo")
                        .HasForeignKey("QLSach.database.models.Photo", "book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLSach.database.models.Register", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.HasOne("QLSach.dbContext.models.author", "author")
                        .WithOne("Book")
                        .HasForeignKey("QLSach.dbContext.models.Book", "author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("author");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Navigation("bookInteraction")
                        .IsRequired();

                    b.Navigation("childrents");
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("photo");
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
