// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSach.database;

#nullable disable

namespace QLSach.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241030135407_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("liked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<bool>("saved")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookInteractions");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.HasIndex("parent_id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 13,
                            UserId = 7,
                            content = "Rem labore ex."
                        },
                        new
                        {
                            Id = 2,
                            BookId = 13,
                            UserId = 8,
                            content = "Vitae quas a ipsum qui consectetur."
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            UserId = 6,
                            content = "Laboriosam velit eligendi temporibus minima non dicta."
                        },
                        new
                        {
                            Id = 4,
                            BookId = 12,
                            UserId = 6,
                            content = "Est nam aperiam similique."
                        },
                        new
                        {
                            Id = 5,
                            BookId = 15,
                            UserId = 14,
                            content = "Et ipsum eligendi rerum."
                        },
                        new
                        {
                            Id = 6,
                            BookId = 18,
                            UserId = 14,
                            content = "Nisi vero quos qui corrupti repellendus et aspernatur alias."
                        },
                        new
                        {
                            Id = 7,
                            BookId = 13,
                            UserId = 16,
                            content = "Quia aut doloribus aliquam velit rerum impedit quidem enim."
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            UserId = 4,
                            content = "Dicta debitis et quam ut itaque et accusamus occaecati eaque."
                        },
                        new
                        {
                            Id = 9,
                            BookId = 28,
                            UserId = 10,
                            content = "Reprehenderit quo consequuntur labore ut recusandae explicabo laudantium asperiores minus."
                        },
                        new
                        {
                            Id = 10,
                            BookId = 3,
                            UserId = 15,
                            content = "Sit natus aut et."
                        },
                        new
                        {
                            Id = 11,
                            BookId = 28,
                            UserId = 4,
                            content = "Non eaque suscipit error natus provident nulla nulla modi quos."
                        },
                        new
                        {
                            Id = 12,
                            BookId = 21,
                            UserId = 12,
                            content = "Qui unde sequi quia doloremque sit ad."
                        },
                        new
                        {
                            Id = 13,
                            BookId = 30,
                            UserId = 16,
                            content = "Minima sed provident asperiores magni consequuntur."
                        },
                        new
                        {
                            Id = 14,
                            BookId = 7,
                            UserId = 11,
                            content = "Iusto dolor est."
                        },
                        new
                        {
                            Id = 15,
                            BookId = 5,
                            UserId = 13,
                            content = "Aut optio adipisci hic tenetur assumenda aut placeat suscipit ut."
                        },
                        new
                        {
                            Id = 16,
                            BookId = 18,
                            UserId = 11,
                            content = "A illo explicabo veritatis est corrupti quae."
                        },
                        new
                        {
                            Id = 17,
                            BookId = 22,
                            UserId = 9,
                            content = "Quod perspiciatis occaecati possimus voluptatum consequatur architecto dolor amet et.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 18,
                            BookId = 5,
                            UserId = 10,
                            content = "Fuga veniam nesciunt.",
                            parent_id = 15
                        },
                        new
                        {
                            Id = 19,
                            BookId = 28,
                            UserId = 5,
                            content = "Est tempore natus totam velit facere eum vitae.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 20,
                            BookId = 6,
                            UserId = 12,
                            content = "Minima sit neque totam laborum illo pariatur odio dignissimos voluptas.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 21,
                            BookId = 27,
                            UserId = 4,
                            content = "Incidunt et asperiores laudantium non ab sunt doloribus omnis dolorem.",
                            parent_id = 10
                        },
                        new
                        {
                            Id = 22,
                            BookId = 23,
                            UserId = 16,
                            content = "Fugiat incidunt molestiae magni excepturi dolorem fuga est omnis voluptas.",
                            parent_id = 2
                        },
                        new
                        {
                            Id = 23,
                            BookId = 27,
                            UserId = 2,
                            content = "Magnam quae natus harum quos sint.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 24,
                            BookId = 25,
                            UserId = 15,
                            content = "Perferendis non et consequatur autem quam quod nobis veniam cumque.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 25,
                            BookId = 13,
                            UserId = 2,
                            content = "Perferendis quos reiciendis voluptatem ea facilis sed aliquam enim.",
                            parent_id = 5
                        },
                        new
                        {
                            Id = 26,
                            BookId = 18,
                            UserId = 9,
                            content = "Illo quo omnis deserunt sit reprehenderit.",
                            parent_id = 15
                        },
                        new
                        {
                            Id = 27,
                            BookId = 12,
                            UserId = 13,
                            content = "Ab perferendis exercitationem et.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 28,
                            BookId = 10,
                            UserId = 10,
                            content = "Aperiam rerum amet.",
                            parent_id = 3
                        },
                        new
                        {
                            Id = 29,
                            BookId = 27,
                            UserId = 7,
                            content = "Repudiandae sed aliquam inventore expedita deleniti sint et sed magnam.",
                            parent_id = 6
                        },
                        new
                        {
                            Id = 30,
                            BookId = 15,
                            UserId = 8,
                            content = "Soluta praesentium dolores qui qui.",
                            parent_id = 3
                        },
                        new
                        {
                            Id = 31,
                            BookId = 15,
                            UserId = 14,
                            content = "Ea laudantium quia libero perspiciatis cum.",
                            parent_id = 4
                        },
                        new
                        {
                            Id = 32,
                            BookId = 19,
                            UserId = 5,
                            content = "Aliquam possimus omnis cumque eos minus cumque rem aut unde.",
                            parent_id = 10
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.Property<string>("path")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.HasKey("path");

                    b.HasIndex("book_id")
                        .IsUnique();

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            path = "1fake path",
                            book_id = 12
                        },
                        new
                        {
                            path = "2fake path",
                            book_id = 9
                        },
                        new
                        {
                            path = "3fake path",
                            book_id = 14
                        },
                        new
                        {
                            path = "4fake path",
                            book_id = 7
                        },
                        new
                        {
                            path = "5fake path",
                            book_id = 3
                        },
                        new
                        {
                            path = "6fake path",
                            book_id = 16
                        },
                        new
                        {
                            path = "7fake path",
                            book_id = 22
                        },
                        new
                        {
                            path = "8fake path",
                            book_id = 27
                        },
                        new
                        {
                            path = "9fake path",
                            book_id = 10
                        },
                        new
                        {
                            path = "10fake path",
                            book_id = 6
                        },
                        new
                        {
                            path = "11fake path",
                            book_id = 15
                        },
                        new
                        {
                            path = "12fake path",
                            book_id = 29
                        },
                        new
                        {
                            path = "13fake path",
                            book_id = 3
                        },
                        new
                        {
                            path = "14fake path",
                            book_id = 22
                        },
                        new
                        {
                            path = "15fake path",
                            book_id = 15
                        },
                        new
                        {
                            path = "16fake path",
                            book_id = 14
                        });
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "nihil",
                            UserName = "Lori Heidenreich"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Et voluptas suscipit voluptatibus id cumque repellat ut ipsum sint. Consectetur ea delectus nihil natus. Consequatur et enim officia. Eaque laborum incidunt odio voluptatem sed quia sit quia a. Aut aut quasi reprehenderit quasi. Quisquam totam harum non tenetur.",
                            UserName = "Sidney Wintheiser"
                        },
                        new
                        {
                            Id = 3,
                            Password = "et",
                            UserName = "Lincoln Greenholt"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Enim vel sapiente dolorum qui quia natus.",
                            UserName = "Minnie Simonis"
                        },
                        new
                        {
                            Id = 5,
                            Password = "Voluptas sit eligendi magnam rerum. Eos et culpa architecto quia eos ut modi. Temporibus unde magni et. Similique occaecati architecto expedita reiciendis praesentium ab. Eius error similique vero dicta laudantium consectetur rerum nihil esse. Quia repellendus tempore et enim totam exercitationem quae est neque.",
                            UserName = "Roselyn Berge"
                        },
                        new
                        {
                            Id = 6,
                            Password = "Et rerum id fugit. Quia ipsa veritatis dolorem ut quia quidem eos voluptatibus blanditiis. Nihil qui ex doloremque eaque asperiores nobis doloribus alias consequatur. Necessitatibus veniam numquam et autem expedita. Ipsum at consequatur voluptates ab molestias.",
                            UserName = "Laverne Labadie"
                        },
                        new
                        {
                            Id = 7,
                            Password = "Quisquam id consequatur amet.\nItaque ut aut eveniet enim sit et velit expedita.",
                            UserName = "Roxanne Bahringer"
                        },
                        new
                        {
                            Id = 8,
                            Password = "quis",
                            UserName = "Evert Corwin"
                        },
                        new
                        {
                            Id = 9,
                            Password = "occaecati",
                            UserName = "Roderick Johnston"
                        },
                        new
                        {
                            Id = 10,
                            Password = "Sed quidem ut explicabo repellendus.",
                            UserName = "Dena Turner"
                        },
                        new
                        {
                            Id = 11,
                            Password = "Quasi libero sit autem omnis. Ipsum accusamus provident ad quia porro libero nisi blanditiis. Maiores blanditiis velit est qui ducimus odit libero.",
                            UserName = "Aron Mayer"
                        },
                        new
                        {
                            Id = 12,
                            Password = "Aut ad quia enim consectetur tempore est inventore dolorum numquam.",
                            UserName = "Kadin McCullough"
                        },
                        new
                        {
                            Id = 13,
                            Password = "Dolore omnis et dolores et earum.\nNam alias nobis iure facere recusandae veritatis id modi.\nRepudiandae quas dignissimos voluptas rerum qui.",
                            UserName = "Lorna Harris"
                        },
                        new
                        {
                            Id = 14,
                            Password = "Pariatur quis occaecati ipsa. Error laudantium eum et minus ut occaecati. Maiores dolores nam reiciendis. Velit dolorem temporibus ut iure et aut. Quis nisi veniam officiis iure et eligendi deleniti consequatur. Sunt debitis eaque optio dolores sunt itaque.",
                            UserName = "Gerald Spinka"
                        },
                        new
                        {
                            Id = 15,
                            Password = "Velit nihil nesciunt sint accusamus tempora aut sunt velit quis. Quaerat iste dolorum ea eum est quae quas. Quia exercitationem vero sit. Eum similique iusto dolores et aut.",
                            UserName = "America Graham"
                        },
                        new
                        {
                            Id = 16,
                            Password = "Sint tempore necessitatibus.",
                            UserName = "Brad Thiel"
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("author_id")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            author_id = 1,
                            description = "Laudantium qui vitae eos eos nisi facilis nulla nam. Doloremque beatae labore ut voluptatibus autem consequuntur atque et. Eum vel facere architecto eum non reprehenderit. Ea maiores consectetur aut nihil ullam.",
                            name = "Odit voluptatem facere.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            author_id = 7,
                            description = "Exercitationem molestias in fugit voluptatem nemo. Dolor rem dolores molestias cumque vitae eos ipsum reprehenderit. Quo sit provident atque. Quis quisquam mollitia et tenetur quisquam sed incidunt.",
                            name = "Ut distinctio aliquid omnis voluptate distinctio aut consectetur soluta.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 3,
                            author_id = 32,
                            description = "Voluptatem ut vero ipsam ea qui sit. Provident excepturi culpa praesentium beatae sed quasi. Ipsum aperiam voluptatem quae sit nisi architecto iusto. Non qui inventore et sed dolorem non.",
                            name = "Reiciendis sed qui quos veniam et repellendus.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 4,
                            author_id = 19,
                            description = "Dicta aperiam ipsum necessitatibus vitae quia praesentium asperiores nemo. Aliquam sint consectetur. Eos pariatur rem ut totam magnam soluta. Molestias voluptatem aut facere adipisci ipsa maiores repellat. Provident laboriosam aperiam. Non facere rem aliquid voluptas et rerum consequatur.",
                            name = "Magnam hic quia.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 5,
                            author_id = 28,
                            description = "Aut dolorem sit assumenda non blanditiis et deserunt. Tenetur autem accusamus qui. Dolorem aliquid dolore qui. Maiores officiis temporibus.",
                            name = "Ut aliquid asperiores natus officia est at distinctio eveniet.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 6,
                            author_id = 15,
                            description = "Ab facere quod aliquam aut. Et laudantium aliquid excepturi eum optio rerum. Tempore est quia possimus.",
                            name = "Explicabo ipsa doloribus repellat excepturi cum.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 7,
                            author_id = 12,
                            description = "Inventore accusamus alias reiciendis alias et ut. Incidunt consectetur odio. Autem vero et voluptatem qui rerum.",
                            name = "Aut ex delectus.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 8,
                            author_id = 11,
                            description = "Blanditiis rem illo aspernatur. Sequi eaque necessitatibus perferendis ipsum. Non facere iusto. Odio laboriosam nisi quibusdam facilis quis ea et omnis error. Ut aut laudantium aliquam sit porro.",
                            name = "Et illum non esse.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 9,
                            author_id = 6,
                            description = "Rerum distinctio enim nobis non dolor sit et nihil suscipit. Id enim sint consequatur nihil sed quia et numquam. Aut fugiat ab minima. Accusantium dolores veniam officia aut dolor. Magnam dolores explicabo illum. Dolores asperiores odit non.",
                            name = "Minima temporibus et quis incidunt maxime exercitationem autem quia.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 10,
                            author_id = 4,
                            description = "Et itaque aut omnis blanditiis provident. Quaerat saepe illo odit qui rem qui quaerat ab. Accusamus aliquam rerum suscipit nisi voluptatem magnam.",
                            name = "Maxime labore modi incidunt recusandae ut voluptate ut.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 11,
                            author_id = 25,
                            description = "Quis quidem sequi est. Eaque distinctio consequatur. Rerum nihil et.",
                            name = "Ex dignissimos eveniet.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 12,
                            author_id = 17,
                            description = "Reprehenderit et aut et voluptatem aut vel. Nemo aut molestias consequatur quam dolorem odit. Nisi ut quia repudiandae reprehenderit porro repudiandae aut. Soluta molestiae repellendus ut numquam quia aut omnis optio. Debitis suscipit voluptatem laudantium dolor. Nisi vel ipsam corporis suscipit cum in illo inventore at.",
                            name = "Nobis omnis laudantium iusto.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 13,
                            author_id = 9,
                            description = "Reprehenderit deleniti quia quibusdam veniam excepturi sed sint iure. Soluta consequuntur dolorem odio inventore et ut inventore at labore. Labore adipisci quod magni minus labore quo. Deserunt aut distinctio quo quaerat consequatur a quis qui.",
                            name = "Unde qui sint ut animi fugiat odio in.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 14,
                            author_id = 6,
                            description = "Velit dolorem neque. Necessitatibus repudiandae fuga qui autem veritatis. Corporis non incidunt cumque ad doloremque quod. Sunt ratione vel aut totam.",
                            name = "Sequi dolor adipisci perspiciatis maxime rerum molestiae.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 15,
                            author_id = 30,
                            description = "Quo tempora velit quaerat non ex est laudantium error. Ea dignissimos nobis qui et. Commodi beatae quas quam. Doloremque minima ducimus dolor.",
                            name = "Omnis voluptatem consectetur iste mollitia.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 16,
                            author_id = 1,
                            description = "Assumenda expedita fugiat. Est vitae sunt explicabo quia temporibus magnam minima. Deleniti unde quia autem necessitatibus est qui. Sit et repellendus voluptate eum nihil dolorem quas est unde.",
                            name = "Suscipit aut omnis iusto reprehenderit nihil.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 17,
                            author_id = 23,
                            description = "Veritatis voluptatem odio sapiente mollitia voluptas rerum rerum quia aut. Similique beatae quidem omnis rerum saepe voluptates rerum itaque at. Aut autem voluptatem eum quis provident aut eum reprehenderit sapiente. Reprehenderit tenetur ex illo.",
                            name = "Laborum sint ex quaerat ea repudiandae nulla ut aut.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 18,
                            author_id = 12,
                            description = "Laboriosam eius aut sequi praesentium voluptatibus qui. Dolorem est doloremque sed nihil aut. Maiores et voluptate est quidem ut blanditiis quia. Est rerum maxime.",
                            name = "Asperiores error accusamus dolore dignissimos non.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 19,
                            author_id = 28,
                            description = "Qui eveniet quo eos expedita vero. Consequatur veniam nostrum. Assumenda eos qui nemo nam tenetur minima molestiae. Non voluptatibus et doloribus et vel. Sed culpa est accusantium et rerum delectus veniam. Hic accusamus et.",
                            name = "Enim quis alias exercitationem.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 20,
                            author_id = 22,
                            description = "Explicabo perspiciatis quod rerum ea nemo. Quos autem rerum nobis ipsum qui. Et suscipit numquam quis quaerat enim esse rem.",
                            name = "Architecto vero dolorem vel fugiat eius fugit.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 21,
                            author_id = 21,
                            description = "Laudantium excepturi esse ut sunt unde ut alias. Ut et ab sit enim dolor atque non dolore. Nemo ratione quia consequatur voluptatem et omnis asperiores soluta. Dolorum amet sapiente sint. Sint ratione necessitatibus perferendis soluta. Rem ad quisquam.",
                            name = "Nemo ipsam libero culpa ut dolor suscipit maxime praesentium ut.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 22,
                            author_id = 2,
                            description = "Consequatur enim provident est sed dolorem. Laborum quisquam quod voluptatem ea. Veritatis nemo repellendus. Earum exercitationem atque provident cupiditate. Occaecati quia architecto voluptatibus doloremque. Voluptatem cumque rem qui consequuntur nulla.",
                            name = "Vel eos error a ut incidunt nisi laborum qui.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 23,
                            author_id = 26,
                            description = "Ad porro ea. Consequuntur in ex voluptatum eligendi ut totam distinctio voluptatem. Reprehenderit pariatur iusto qui mollitia similique ut placeat minima quas. Ut et voluptates nostrum omnis labore dolorem et voluptas quasi. Nihil placeat quia. Deleniti totam facilis expedita.",
                            name = "Laborum est cupiditate dolores esse et sed voluptatem ipsam.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 24,
                            author_id = 29,
                            description = "Ut nemo consectetur reprehenderit non qui. Beatae dolores explicabo inventore. Quod a exercitationem amet illo accusamus. Cupiditate voluptate libero. Sit labore sed.",
                            name = "Fugit repellat et.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 25,
                            author_id = 3,
                            description = "Id ut explicabo est culpa. Magni inventore quia dolore numquam. Nostrum sit omnis at sit. Quae aut et sunt vel.",
                            name = "Distinctio sint nesciunt laudantium accusamus fuga nisi.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 26,
                            author_id = 19,
                            description = "Quam eaque quam voluptates doloribus dolores consequuntur. Excepturi et ut nobis. Veritatis molestias dignissimos praesentium rerum iure sunt et aut at.",
                            name = "Provident et et.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 27,
                            author_id = 1,
                            description = "Tenetur omnis perspiciatis aliquid consequatur quo doloribus facilis. Et delectus enim. Dolorum at et blanditiis deleniti maiores. Molestiae dolor enim deleniti. Consequatur minima aut esse natus omnis vel sit nesciunt et.",
                            name = "Error dolore odit non maiores provident ipsum explicabo aliquid.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 28,
                            author_id = 29,
                            description = "Autem totam repellendus numquam non. Quod aliquid maiores dolorem voluptas nemo ut est. Voluptatem eaque autem ipsa possimus maxime optio ut. In totam aut eius pariatur sit eum magnam quia. Est itaque totam ut id cupiditate. Numquam et aut tempore ab ab laboriosam.",
                            name = "Enim iure odio dolores numquam qui sed.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 29,
                            author_id = 17,
                            description = "Et nesciunt corporis repudiandae. Harum ut repudiandae dignissimos. Facere cum quia. Molestiae ducimus ea pariatur accusantium quia et et. Omnis voluptatem repellat et odit sunt fugit tempore eius.",
                            name = "Delectus dolores vero soluta totam molestiae dignissimos.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 30,
                            author_id = 10,
                            description = "Illum nam totam velit quas officiis qui rerum magni. Tempore voluptatem veritatis excepturi. At deleniti debitis accusamus autem mollitia. Voluptatem rerum adipisci enim iste non. Maiores est qui quia modi animi eum ut eos. Dolorem corrupti minus voluptatem nesciunt velit voluptatem voluptas expedita molestiae.",
                            name = "Error amet porro officia et.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 31,
                            author_id = 24,
                            description = "Vitae explicabo dolor. Aspernatur optio est hic excepturi ducimus et enim. Voluptas laudantium quidem ex amet accusamus itaque autem.",
                            name = "Eum aperiam dolorem sapiente dolorum nostrum repellat est ea voluptas.",
                            rating = (byte)0
                        },
                        new
                        {
                            Id = 32,
                            author_id = 3,
                            description = "Qui sit odio neque ipsa ipsam aspernatur magni qui reiciendis. Assumenda sit reprehenderit sint quisquam non voluptatum consequuntur. Recusandae ea qui. Voluptatem ut vel saepe est alias earum cumque repudiandae atque.",
                            name = "Facilis et enim iure veniam recusandae quod nam.",
                            rating = (byte)0
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Qui ut et et aut.",
                            name = "Esteban"
                        },
                        new
                        {
                            Id = 2,
                            description = "Nisi reprehenderit repellendus odit.",
                            name = "Audreanne"
                        },
                        new
                        {
                            Id = 3,
                            description = "Id autem a qui.",
                            name = "Lisa"
                        },
                        new
                        {
                            Id = 4,
                            description = "Sapiente praesentium repellat recusandae aut eos rerum est eaque velit.",
                            name = "Joy"
                        },
                        new
                        {
                            Id = 5,
                            description = "Et aut sed.",
                            name = "Josiane"
                        },
                        new
                        {
                            Id = 6,
                            description = "Laboriosam explicabo rem sit dolorem commodi nihil quos assumenda a.",
                            name = "Constantin"
                        },
                        new
                        {
                            Id = 7,
                            description = "Rem sed quis.",
                            name = "Lizzie"
                        },
                        new
                        {
                            Id = 8,
                            description = "Sit nihil et aut laborum necessitatibus veritatis ut quis.",
                            name = "Danyka"
                        },
                        new
                        {
                            Id = 9,
                            description = "Alias explicabo et in porro quidem unde.",
                            name = "Blake"
                        },
                        new
                        {
                            Id = 10,
                            description = "Atque nobis rerum.",
                            name = "Lila"
                        },
                        new
                        {
                            Id = 11,
                            description = "Fuga aut aspernatur autem sed dignissimos fuga facere aspernatur aspernatur.",
                            name = "Garrett"
                        },
                        new
                        {
                            Id = 12,
                            description = "Placeat nemo quasi rerum eum vero atque esse.",
                            name = "Damaris"
                        },
                        new
                        {
                            Id = 13,
                            description = "Esse aut expedita sunt a nobis est voluptatum.",
                            name = "Darlene"
                        },
                        new
                        {
                            Id = 14,
                            description = "In minus quia nam voluptatem dolorem.",
                            name = "Isaias"
                        },
                        new
                        {
                            Id = 15,
                            description = "Ipsam mollitia laboriosam labore at consequatur aperiam.",
                            name = "Lacey"
                        },
                        new
                        {
                            Id = 16,
                            description = "Ipsa qui dicta aut quis.",
                            name = "Mariano"
                        },
                        new
                        {
                            Id = 17,
                            description = "Dolor temporibus praesentium inventore quia quibusdam.",
                            name = "Antoinette"
                        },
                        new
                        {
                            Id = 18,
                            description = "Ut occaecati consequatur totam velit ducimus autem quis et.",
                            name = "Weston"
                        },
                        new
                        {
                            Id = 19,
                            description = "Atque eum aut.",
                            name = "Loraine"
                        },
                        new
                        {
                            Id = 20,
                            description = "Natus voluptatem aut dolores.",
                            name = "Emmanuel"
                        },
                        new
                        {
                            Id = 21,
                            description = "Sunt nulla illum eum aut quisquam blanditiis omnis.",
                            name = "Alexzander"
                        },
                        new
                        {
                            Id = 22,
                            description = "Esse laborum corporis.",
                            name = "Carole"
                        },
                        new
                        {
                            Id = 23,
                            description = "Distinctio atque vitae facilis unde quae optio.",
                            name = "Jordane"
                        },
                        new
                        {
                            Id = 24,
                            description = "Quisquam perspiciatis ipsa.",
                            name = "Fredrick"
                        },
                        new
                        {
                            Id = 25,
                            description = "Aut reprehenderit in.",
                            name = "Eulah"
                        },
                        new
                        {
                            Id = 26,
                            description = "Dignissimos deleniti amet libero tenetur.",
                            name = "Fern"
                        },
                        new
                        {
                            Id = 27,
                            description = "Ut et eos molestiae eum aut modi.",
                            name = "Eliza"
                        },
                        new
                        {
                            Id = 28,
                            description = "Ea minus et.",
                            name = "Brody"
                        },
                        new
                        {
                            Id = 29,
                            description = "Deleniti et qui ea aliquam sequi deserunt voluptatibus nostrum iusto.",
                            name = "Camden"
                        },
                        new
                        {
                            Id = 30,
                            description = "Quod vel dignissimos exercitationem nostrum rerum quasi ut.",
                            name = "Kristy"
                        },
                        new
                        {
                            Id = 31,
                            description = "Occaecati esse sequi atque perferendis voluptas magni.",
                            name = "Malvina"
                        },
                        new
                        {
                            Id = 32,
                            description = "A iste cumque veritatis ex exercitationem quas ut voluptatibus qui.",
                            name = "Ulises"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany("Interactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "comment")
                        .WithOne("bookInteraction")
                        .HasForeignKey("QLSach.database.models.BookInteraction", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "parent")
                        .WithMany("childrents")
                        .HasForeignKey("parent_id");

                    b.Navigation("book");

                    b.Navigation("parent");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "Book")
                        .WithOne("photo")
                        .HasForeignKey("QLSach.database.models.Photo", "book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.HasOne("QLSach.dbContext.models.author", "author")
                        .WithOne("Book")
                        .HasForeignKey("QLSach.dbContext.models.Book", "author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Navigation("bookInteraction")
                        .IsRequired();

                    b.Navigation("childrents");
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Interactions");

                    b.Navigation("photo");
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
