// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSach.database;

#nullable disable

namespace QLSach.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241103132431_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("liked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<bool>("saved")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookInteractions");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.HasIndex("parent_id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 22,
                            UserId = 3,
                            content = "Optio minus sed possimus sunt itaque."
                        },
                        new
                        {
                            Id = 2,
                            BookId = 4,
                            UserId = 3,
                            content = "Deleniti nulla sed necessitatibus."
                        },
                        new
                        {
                            Id = 3,
                            BookId = 10,
                            UserId = 3,
                            content = "Architecto quae repellendus expedita ducimus molestiae aspernatur provident."
                        },
                        new
                        {
                            Id = 4,
                            BookId = 10,
                            UserId = 14,
                            content = "Quaerat eos odio officia dicta cum autem iure."
                        },
                        new
                        {
                            Id = 5,
                            BookId = 26,
                            UserId = 6,
                            content = "Et et earum ullam autem temporibus totam quod eos."
                        },
                        new
                        {
                            Id = 6,
                            BookId = 24,
                            UserId = 3,
                            content = "Ut quia dolore ea est dolorem est dolore omnis praesentium."
                        },
                        new
                        {
                            Id = 7,
                            BookId = 27,
                            UserId = 11,
                            content = "At veniam et eligendi nobis perspiciatis veritatis facilis."
                        },
                        new
                        {
                            Id = 8,
                            BookId = 6,
                            UserId = 14,
                            content = "Expedita molestiae aspernatur veritatis assumenda dolorem nesciunt ad quis velit."
                        },
                        new
                        {
                            Id = 9,
                            BookId = 6,
                            UserId = 9,
                            content = "Est adipisci fugiat fugiat."
                        },
                        new
                        {
                            Id = 10,
                            BookId = 20,
                            UserId = 7,
                            content = "Vitae in est nesciunt ullam."
                        },
                        new
                        {
                            Id = 11,
                            BookId = 10,
                            UserId = 10,
                            content = "Nihil pariatur quia sequi autem minus ipsa."
                        },
                        new
                        {
                            Id = 12,
                            BookId = 19,
                            UserId = 6,
                            content = "Enim modi inventore."
                        },
                        new
                        {
                            Id = 13,
                            BookId = 1,
                            UserId = 11,
                            content = "Occaecati dolorem praesentium."
                        },
                        new
                        {
                            Id = 14,
                            BookId = 20,
                            UserId = 13,
                            content = "Voluptatem qui rem sint corporis dolorum et provident aut numquam."
                        },
                        new
                        {
                            Id = 15,
                            BookId = 5,
                            UserId = 12,
                            content = "Et ad molestiae inventore omnis aliquam ut aut."
                        },
                        new
                        {
                            Id = 16,
                            BookId = 25,
                            UserId = 14,
                            content = "Dignissimos eaque est numquam ut occaecati autem ratione quia vel."
                        },
                        new
                        {
                            Id = 17,
                            BookId = 4,
                            UserId = 13,
                            content = "Voluptas nam nesciunt aliquid.",
                            parent_id = 13
                        },
                        new
                        {
                            Id = 18,
                            BookId = 12,
                            UserId = 13,
                            content = "Sequi et iusto sapiente tempore aliquid dolorem voluptatem quo et.",
                            parent_id = 16
                        },
                        new
                        {
                            Id = 19,
                            BookId = 3,
                            UserId = 2,
                            content = "Quia quidem ipsum distinctio repellat quae quis.",
                            parent_id = 16
                        },
                        new
                        {
                            Id = 20,
                            BookId = 21,
                            UserId = 3,
                            content = "Voluptatem velit facere aspernatur.",
                            parent_id = 8
                        },
                        new
                        {
                            Id = 21,
                            BookId = 17,
                            UserId = 13,
                            content = "Non assumenda dolores commodi consequatur praesentium adipisci.",
                            parent_id = 15
                        },
                        new
                        {
                            Id = 22,
                            BookId = 10,
                            UserId = 14,
                            content = "Quasi maiores voluptate aut ducimus est nesciunt culpa.",
                            parent_id = 11
                        },
                        new
                        {
                            Id = 23,
                            BookId = 28,
                            UserId = 4,
                            content = "Ex dolore architecto qui porro et voluptates.",
                            parent_id = 13
                        },
                        new
                        {
                            Id = 24,
                            BookId = 25,
                            UserId = 13,
                            content = "Molestiae odit laborum nostrum esse dolorum excepturi iure.",
                            parent_id = 5
                        },
                        new
                        {
                            Id = 25,
                            BookId = 14,
                            UserId = 1,
                            content = "In ut voluptatem et fugiat et sapiente dolorum.",
                            parent_id = 5
                        },
                        new
                        {
                            Id = 26,
                            BookId = 26,
                            UserId = 7,
                            content = "Illum rem quisquam laboriosam.",
                            parent_id = 12
                        },
                        new
                        {
                            Id = 27,
                            BookId = 14,
                            UserId = 3,
                            content = "Voluptatem et debitis quibusdam.",
                            parent_id = 9
                        },
                        new
                        {
                            Id = 28,
                            BookId = 9,
                            UserId = 16,
                            content = "Enim qui sit error autem vitae voluptate.",
                            parent_id = 5
                        },
                        new
                        {
                            Id = 29,
                            BookId = 12,
                            UserId = 2,
                            content = "Facilis enim laborum culpa eos labore ut alias.",
                            parent_id = 3
                        },
                        new
                        {
                            Id = 30,
                            BookId = 7,
                            UserId = 6,
                            content = "Aut consequatur beatae dolorum et rerum dolor in.",
                            parent_id = 6
                        },
                        new
                        {
                            Id = 31,
                            BookId = 20,
                            UserId = 9,
                            content = "Consequatur laboriosam pariatur placeat vel repudiandae et omnis enim.",
                            parent_id = 2
                        },
                        new
                        {
                            Id = 32,
                            BookId = 28,
                            UserId = 3,
                            content = "Eveniet aspernatur minus et est beatae earum repellendus quibusdam qui.",
                            parent_id = 16
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "earum"
                        },
                        new
                        {
                            id = 2,
                            name = "nulla"
                        },
                        new
                        {
                            id = 3,
                            name = "possimus"
                        },
                        new
                        {
                            id = 4,
                            name = "et"
                        },
                        new
                        {
                            id = 5,
                            name = "illo"
                        },
                        new
                        {
                            id = 6,
                            name = "voluptatem"
                        },
                        new
                        {
                            id = 7,
                            name = "distinctio"
                        },
                        new
                        {
                            id = 8,
                            name = "libero"
                        },
                        new
                        {
                            id = 9,
                            name = "veritatis"
                        },
                        new
                        {
                            id = 10,
                            name = "repellendus"
                        },
                        new
                        {
                            id = 11,
                            name = "rerum"
                        },
                        new
                        {
                            id = 12,
                            name = "fugiat"
                        },
                        new
                        {
                            id = 13,
                            name = "veniam"
                        },
                        new
                        {
                            id = 14,
                            name = "soluta"
                        },
                        new
                        {
                            id = 15,
                            name = "et"
                        },
                        new
                        {
                            id = 16,
                            name = "eum"
                        },
                        new
                        {
                            id = 17,
                            name = "quo"
                        },
                        new
                        {
                            id = 18,
                            name = "et"
                        },
                        new
                        {
                            id = 19,
                            name = "sit"
                        },
                        new
                        {
                            id = 20,
                            name = "autem"
                        },
                        new
                        {
                            id = 21,
                            name = "velit"
                        },
                        new
                        {
                            id = 22,
                            name = "veniam"
                        },
                        new
                        {
                            id = 23,
                            name = "animi"
                        },
                        new
                        {
                            id = 24,
                            name = "eius"
                        },
                        new
                        {
                            id = 25,
                            name = "a"
                        },
                        new
                        {
                            id = 26,
                            name = "porro"
                        },
                        new
                        {
                            id = 27,
                            name = "laudantium"
                        },
                        new
                        {
                            id = 28,
                            name = "nihil"
                        },
                        new
                        {
                            id = 29,
                            name = "nam"
                        },
                        new
                        {
                            id = 30,
                            name = "perspiciatis"
                        },
                        new
                        {
                            id = 31,
                            name = "quia"
                        },
                        new
                        {
                            id = 32,
                            name = "dicta"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.Property<string>("path")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.HasKey("path");

                    b.HasIndex("book_id")
                        .IsUnique();

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            path = "1fake path",
                            book_id = 4
                        },
                        new
                        {
                            path = "2fake path",
                            book_id = 12
                        },
                        new
                        {
                            path = "3fake path",
                            book_id = 14
                        },
                        new
                        {
                            path = "4fake path",
                            book_id = 16
                        },
                        new
                        {
                            path = "5fake path",
                            book_id = 23
                        },
                        new
                        {
                            path = "6fake path",
                            book_id = 18
                        },
                        new
                        {
                            path = "7fake path",
                            book_id = 6
                        },
                        new
                        {
                            path = "8fake path",
                            book_id = 23
                        },
                        new
                        {
                            path = "9fake path",
                            book_id = 26
                        },
                        new
                        {
                            path = "10fake path",
                            book_id = 11
                        },
                        new
                        {
                            path = "11fake path",
                            book_id = 19
                        },
                        new
                        {
                            path = "12fake path",
                            book_id = 5
                        },
                        new
                        {
                            path = "13fake path",
                            book_id = 3
                        },
                        new
                        {
                            path = "14fake path",
                            book_id = 27
                        },
                        new
                        {
                            path = "15fake path",
                            book_id = 10
                        },
                        new
                        {
                            path = "16fake path",
                            book_id = 24
                        });
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Sint ex et quaerat similique.",
                            UserName = "Annamae Harber"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Rerum cumque numquam.\nAd necessitatibus qui.\nQuaerat totam consequuntur laborum suscipit.",
                            UserName = "Clemmie Schneider"
                        },
                        new
                        {
                            Id = 3,
                            Password = "sit",
                            UserName = "Dan Block"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Quaerat velit et. Autem sapiente doloremque. Quos voluptatibus quod distinctio. Repudiandae dolorum ad facilis esse. Omnis nam in voluptatum vero.",
                            UserName = "Janis Denesik"
                        },
                        new
                        {
                            Id = 5,
                            Password = "velit",
                            UserName = "Desiree Bashirian"
                        },
                        new
                        {
                            Id = 6,
                            Password = "ipsum",
                            UserName = "Edison Bernhard"
                        },
                        new
                        {
                            Id = 7,
                            Password = "At est quia quaerat voluptas repellat pariatur minus.",
                            UserName = "Cristal Cremin"
                        },
                        new
                        {
                            Id = 8,
                            Password = "Facilis quos sit qui est ullam.",
                            UserName = "Vincenzo Bosco"
                        },
                        new
                        {
                            Id = 9,
                            Password = "voluptatibus",
                            UserName = "Alvah Zieme"
                        },
                        new
                        {
                            Id = 10,
                            Password = "fuga",
                            UserName = "Deborah Murphy"
                        },
                        new
                        {
                            Id = 11,
                            Password = "Magnam excepturi est ipsum saepe eligendi aut dolor quos voluptatibus. Atque et placeat tenetur impedit autem accusamus. Labore velit porro voluptates aut quia eaque quae enim. Dignissimos quam quis autem repellendus distinctio quia a pariatur est.",
                            UserName = "Laurine Krajcik"
                        },
                        new
                        {
                            Id = 12,
                            Password = "Dolor placeat voluptatem repudiandae.",
                            UserName = "Alycia Lynch"
                        },
                        new
                        {
                            Id = 13,
                            Password = "Fugiat cumque esse fugiat illum repellendus illum eos iste reprehenderit.",
                            UserName = "Aliya Robel"
                        },
                        new
                        {
                            Id = 14,
                            Password = "Harum qui nulla itaque laudantium minus.\nQuis vel earum.\nCorporis vero quos voluptatum unde rerum.\nDoloribus est ut nihil.",
                            UserName = "Lee Funk"
                        },
                        new
                        {
                            Id = 15,
                            Password = "Placeat temporibus soluta unde.\nMagni consequatur et nostrum quasi unde sequi iste excepturi nihil.",
                            UserName = "Bert O'Hara"
                        },
                        new
                        {
                            Id = 16,
                            Password = "Odit laborum voluptas recusandae ullam sit ab perspiciatis neque.\nOccaecati ea eos illum sunt ut deleniti dignissimos eligendi dolorem.\nExpedita voluptatem omnis dolores.\nQuas distinctio delectus non hic commodi et magni eum.\nEos aspernatur impedit officia nihil harum nesciunt dolores.\nNon voluptatem at dolor sint blanditiis fugiat voluptas.",
                            UserName = "Ewell Schimmel"
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime?>("created_at"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("genre_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("updated_at")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("year_public")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("author_id")
                        .IsUnique();

                    b.HasIndex("genre_id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            author_id = 12,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(3914),
                            description = "At accusamus fuga incidunt blanditiis nostrum. Cumque alias aut. Qui eligendi non saepe est ad aspernatur consectetur. Quia omnis totam ut sapiente quibusdam voluptatem debitis. Unde minus reiciendis deserunt alias corrupti maiores.",
                            genre_id = 15,
                            name = "Reiciendis consequatur at qui velit tenetur voluptatem occaecati.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(4330),
                            views = 0,
                            year_public = 2023
                        },
                        new
                        {
                            Id = 2,
                            author_id = 21,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5195),
                            description = "Non non in laudantium eum adipisci nemo rerum consequuntur. Est qui id ratione. Et sit corrupti sed omnis sunt. Repellendus aut eum aliquid aut iure in. Consequuntur ex in dolor nulla consectetur nihil quo voluptatem cupiditate.",
                            genre_id = 23,
                            name = "Sequi necessitatibus optio tempora.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5359),
                            views = 0,
                            year_public = 1956
                        },
                        new
                        {
                            Id = 3,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5375),
                            description = "Ut doloribus dolor veniam sit sit dolorem eum nemo ea. Accusantium eaque animi vel possimus. Est deserunt non et explicabo accusamus dolores commodi. Autem aut laboriosam voluptates veritatis.",
                            genre_id = 29,
                            name = "Et aut soluta.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5472),
                            views = 0,
                            year_public = 1918
                        },
                        new
                        {
                            Id = 4,
                            author_id = 26,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5483),
                            description = "Rerum vitae omnis sunt deserunt rerum illo eos non. Dolores quam eius sed dolor qui temporibus et. Rerum sed temporibus dolorum quod voluptas illum. Perspiciatis praesentium qui aut mollitia earum facere explicabo.",
                            genre_id = 17,
                            name = "Temporibus nam doloribus molestias sunt nostrum quis incidunt.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5593),
                            views = 0,
                            year_public = 1937
                        },
                        new
                        {
                            Id = 5,
                            author_id = 29,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5604),
                            description = "Unde ad maiores possimus. Aliquid labore vel architecto laudantium ut corrupti et. Molestiae similique fugit minus minima.",
                            genre_id = 21,
                            name = "Quia praesentium vel quam quia nostrum unde quia dolorem.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5675),
                            views = 0,
                            year_public = 1972
                        },
                        new
                        {
                            Id = 6,
                            author_id = 28,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5686),
                            description = "Exercitationem error quisquam necessitatibus modi maiores corrupti. Tempore ullam quam et ut quia sit. Consectetur est fugit eius excepturi quia ab temporibus.",
                            genre_id = 15,
                            name = "Et aut ea tempora eius.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5763),
                            views = 0,
                            year_public = 1973
                        },
                        new
                        {
                            Id = 7,
                            author_id = 15,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5774),
                            description = "Ipsum consequatur nihil inventore. Nemo qui ipsa suscipit. Quod sit id quaerat iste adipisci ipsam.",
                            genre_id = 13,
                            name = "Aut dolores velit quia autem et.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5836),
                            views = 0,
                            year_public = 2009
                        },
                        new
                        {
                            Id = 8,
                            author_id = 27,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5847),
                            description = "Consequatur tenetur vel suscipit consequatur est magnam nihil qui. Consequuntur ut velit provident. Voluptas possimus voluptatem illum aperiam consequatur aliquam qui consequatur optio. Blanditiis eos omnis impedit ut commodi et velit aperiam est.",
                            genre_id = 9,
                            name = "Et consequuntur aut.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5947),
                            views = 0,
                            year_public = 1993
                        },
                        new
                        {
                            Id = 9,
                            author_id = 5,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(5959),
                            description = "Officia qui culpa mollitia pariatur reiciendis voluptatibus similique. Et vero tempore. Modi id officiis modi. Porro omnis in impedit quaerat assumenda nihil recusandae quis labore.",
                            genre_id = 11,
                            name = "Consequatur autem fuga voluptatem perferendis voluptatibus nemo.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6047),
                            views = 0,
                            year_public = 1948
                        },
                        new
                        {
                            Id = 10,
                            author_id = 20,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6058),
                            description = "Error explicabo magni sequi. Nesciunt provident reiciendis. Facere cum ex dignissimos non quo quia beatae.",
                            genre_id = 28,
                            name = "Voluptas sint possimus id similique.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6118),
                            views = 0,
                            year_public = 1910
                        },
                        new
                        {
                            Id = 11,
                            author_id = 21,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6128),
                            description = "Possimus dignissimos quae quaerat a. Inventore soluta dignissimos itaque repudiandae qui molestiae blanditiis voluptates rerum. Natus possimus adipisci sapiente sed quos cupiditate voluptatem autem.",
                            genre_id = 10,
                            name = "Ut facilis modi necessitatibus molestias modi.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6211),
                            views = 0,
                            year_public = 1918
                        },
                        new
                        {
                            Id = 12,
                            author_id = 4,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6222),
                            description = "Expedita illo dolor sed porro est vel. Dolor consequatur similique et eum doloribus architecto quia. Et asperiores sed ipsum natus autem. Sint doloribus pariatur labore iure. Sunt facilis architecto nisi aut. Dolorem eum id.",
                            genre_id = 18,
                            name = "Fuga culpa ex omnis eveniet.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6345),
                            views = 0,
                            year_public = 1912
                        },
                        new
                        {
                            Id = 13,
                            author_id = 23,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6357),
                            description = "Omnis voluptate quaerat odio aliquam eius sunt. Praesentium repudiandae non reprehenderit. Laborum modi perferendis. Nam quidem sint voluptatem impedit suscipit aut mollitia accusamus. Minus alias vel repellendus.",
                            genre_id = 25,
                            name = "Qui harum molestiae natus amet.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6445),
                            views = 0,
                            year_public = 1929
                        },
                        new
                        {
                            Id = 14,
                            author_id = 11,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6456),
                            description = "Recusandae ipsa similique officiis. Expedita eos unde ipsum minus qui porro. Rerum enim rem ipsam.",
                            genre_id = 11,
                            name = "Rerum ut unde magni vel sint suscipit et.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6518),
                            views = 0,
                            year_public = 1928
                        },
                        new
                        {
                            Id = 15,
                            author_id = 14,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6544),
                            description = "Placeat commodi ipsa excepturi fugit aut. Aut dolorum aut laborum at et maiores nam. Sed in sit ea qui facilis minima. Optio beatae nemo assumenda perspiciatis ut. Et et iusto ullam aut quo. Tempora eius a eum nobis rerum dolor.",
                            genre_id = 8,
                            name = "Laudantium qui consequatur quo quisquam libero molestias iusto.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6664),
                            views = 0,
                            year_public = 2004
                        },
                        new
                        {
                            Id = 16,
                            author_id = 15,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6675),
                            description = "Labore eos sed quia recusandae. Ad mollitia sed. Autem molestiae asperiores. Nulla dolor et. Id veniam nam voluptatem minima omnis.",
                            genre_id = 16,
                            name = "Saepe quia distinctio.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6758),
                            views = 0,
                            year_public = 1946
                        },
                        new
                        {
                            Id = 17,
                            author_id = 29,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6770),
                            description = "Error laborum dolores libero unde possimus blanditiis et et temporibus. Occaecati nisi neque molestiae enim commodi. Accusamus omnis enim est minus velit. Ipsum consequatur blanditiis rerum. Ut sunt atque a sit laudantium quia et porro.",
                            genre_id = 2,
                            name = "Vero nihil delectus natus explicabo enim.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6870),
                            views = 0,
                            year_public = 1907
                        },
                        new
                        {
                            Id = 18,
                            author_id = 3,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6881),
                            description = "Laudantium culpa ut quas accusamus officia ut inventore. Doloremque laboriosam fuga ut in. Debitis omnis voluptas cupiditate porro eaque quaerat fugiat non sequi. Sunt et ex.",
                            genre_id = 21,
                            name = "Sed maiores optio maiores dolor laboriosam est eligendi esse neque.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6971),
                            views = 0,
                            year_public = 1932
                        },
                        new
                        {
                            Id = 19,
                            author_id = 4,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(6982),
                            description = "Qui laboriosam et accusantium alias consequuntur ratione voluptatum quam. Consequatur doloribus asperiores beatae ut. Adipisci quasi vel voluptas dolorum et. Minima dolorem aut.",
                            genre_id = 19,
                            name = "Soluta ab et et tempora et.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7067),
                            views = 0,
                            year_public = 1904
                        },
                        new
                        {
                            Id = 20,
                            author_id = 6,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7077),
                            description = "Consectetur et expedita sit dolorum ut est ad saepe. Voluptate dolorum sunt hic. Eum repellat velit illum.",
                            genre_id = 32,
                            name = "Dolor molestiae at quas pariatur.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7139),
                            views = 0,
                            year_public = 1970
                        },
                        new
                        {
                            Id = 21,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7151),
                            description = "Aut et ut fugit placeat voluptatem fugiat commodi ut architecto. Aliquid totam aut ducimus aliquam maxime iusto vero dolorem. Sit aut dolorem quibusdam tenetur cupiditate impedit quibusdam vero.",
                            genre_id = 8,
                            name = "Voluptas sint dicta et aut iure consequuntur dolorem voluptatibus magnam.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7246),
                            views = 0,
                            year_public = 1949
                        },
                        new
                        {
                            Id = 22,
                            author_id = 24,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7257),
                            description = "Tenetur assumenda quia enim rerum rem porro voluptatem. Dolores et quos et quis expedita qui et qui. Et non atque praesentium omnis. Voluptatem reprehenderit et perferendis ea odit repellendus mollitia earum sed.",
                            genre_id = 27,
                            name = "Tempore rerum asperiores.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7357),
                            views = 0,
                            year_public = 1957
                        },
                        new
                        {
                            Id = 23,
                            author_id = 2,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7368),
                            description = "Cumque dolores et omnis omnis debitis omnis ut porro. Perferendis cum ullam et amet. Consectetur omnis veritatis commodi atque tenetur nemo dignissimos. Magnam ut veritatis maiores.",
                            genre_id = 30,
                            name = "Debitis ut sit.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7456),
                            views = 0,
                            year_public = 1923
                        },
                        new
                        {
                            Id = 24,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7469),
                            description = "Qui voluptas corrupti reprehenderit hic veritatis quis sunt. Rerum sunt omnis quae sapiente. Accusamus et sit temporibus placeat. Molestiae consequatur reiciendis voluptatem enim accusamus et necessitatibus. Sit quis et labore molestias quia in veritatis qui est.",
                            genre_id = 25,
                            name = "Velit corporis velit voluptatibus quisquam aut est ipsam nobis ullam.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7588),
                            views = 0,
                            year_public = 1953
                        },
                        new
                        {
                            Id = 25,
                            author_id = 5,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7599),
                            description = "Blanditiis cumque molestiae mollitia ex doloremque. Omnis perferendis in odit. Quia nulla eos quia. Minima voluptates et repudiandae.",
                            genre_id = 1,
                            name = "Accusantium esse pariatur ducimus quam.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7671),
                            views = 0,
                            year_public = 1922
                        },
                        new
                        {
                            Id = 26,
                            author_id = 14,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7683),
                            description = "Vero et voluptatem et. Temporibus ea nam. Temporibus consectetur blanditiis et praesentium vitae eum illum.",
                            genre_id = 17,
                            name = "Sit explicabo sed dolorum optio voluptatem.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7745),
                            views = 0,
                            year_public = 2019
                        },
                        new
                        {
                            Id = 27,
                            author_id = 30,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7756),
                            description = "Qui sed dolores deleniti ea mollitia nihil et. Ea nobis ipsa sit nihil quia. Quia quia consequatur molestiae et itaque earum porro repudiandae repudiandae.",
                            genre_id = 4,
                            name = "Dicta expedita rerum dolores dolorem ex dolore.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7838),
                            views = 0,
                            year_public = 1912
                        },
                        new
                        {
                            Id = 28,
                            author_id = 4,
                            created_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7849),
                            description = "Ut est minima eos pariatur voluptatibus dolor. Quos non nobis molestiae voluptates. Facilis perspiciatis tempora nemo rem eveniet praesentium.",
                            genre_id = 9,
                            name = "Dolor totam vero corrupti impedit.",
                            rating = (byte)0,
                            updated_at = new DateTime(2024, 11, 3, 20, 24, 30, 908, DateTimeKind.Local).AddTicks(7913),
                            views = 0,
                            year_public = 1939
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Laboriosam explicabo voluptatum recusandae tenetur repellendus sit dolor dolor maiores.",
                            name = "Elnora"
                        },
                        new
                        {
                            Id = 2,
                            description = "Sit perspiciatis voluptatem non.",
                            name = "Robin"
                        },
                        new
                        {
                            Id = 3,
                            description = "Accusamus sed aut occaecati modi.",
                            name = "Shania"
                        },
                        new
                        {
                            Id = 4,
                            description = "Sed excepturi sit nemo est fugit quibusdam.",
                            name = "Stuart"
                        },
                        new
                        {
                            Id = 5,
                            description = "Sit laudantium minus quis eligendi facere ut et tempora.",
                            name = "Terrance"
                        },
                        new
                        {
                            Id = 6,
                            description = "Et reiciendis sequi laudantium est non sed dignissimos.",
                            name = "Arturo"
                        },
                        new
                        {
                            Id = 7,
                            description = "Quo doloribus maxime totam sit.",
                            name = "Tess"
                        },
                        new
                        {
                            Id = 8,
                            description = "Neque voluptas consequatur ipsum impedit dicta quidem non harum.",
                            name = "Jordy"
                        },
                        new
                        {
                            Id = 9,
                            description = "Quidem esse rerum repudiandae dolor earum quia rerum officiis consectetur.",
                            name = "Lauren"
                        },
                        new
                        {
                            Id = 10,
                            description = "Doloribus suscipit alias.",
                            name = "Gregoria"
                        },
                        new
                        {
                            Id = 11,
                            description = "Assumenda soluta quisquam placeat eligendi.",
                            name = "Joel"
                        },
                        new
                        {
                            Id = 12,
                            description = "Ut occaecati ut cum ducimus.",
                            name = "Alberta"
                        },
                        new
                        {
                            Id = 13,
                            description = "Repudiandae qui ipsa veritatis.",
                            name = "Gladyce"
                        },
                        new
                        {
                            Id = 14,
                            description = "Modi numquam libero.",
                            name = "Alexzander"
                        },
                        new
                        {
                            Id = 15,
                            description = "Eos illum aut alias est corporis officiis eos.",
                            name = "Christelle"
                        },
                        new
                        {
                            Id = 16,
                            description = "Odit amet fugiat neque temporibus ab ea perspiciatis.",
                            name = "Laurence"
                        },
                        new
                        {
                            Id = 17,
                            description = "Aliquid est illum delectus adipisci magnam laborum quos praesentium labore.",
                            name = "Salvador"
                        },
                        new
                        {
                            Id = 18,
                            description = "Corrupti vero sit tempore deserunt natus ullam.",
                            name = "Alexandro"
                        },
                        new
                        {
                            Id = 19,
                            description = "Qui beatae quibusdam voluptatem corporis id nihil.",
                            name = "Vesta"
                        },
                        new
                        {
                            Id = 20,
                            description = "Vel et harum.",
                            name = "Angeline"
                        },
                        new
                        {
                            Id = 21,
                            description = "Quae aliquid voluptates atque.",
                            name = "Aurelia"
                        },
                        new
                        {
                            Id = 22,
                            description = "Velit sit fugiat consectetur.",
                            name = "Roma"
                        },
                        new
                        {
                            Id = 23,
                            description = "Autem ut nemo.",
                            name = "Dessie"
                        },
                        new
                        {
                            Id = 24,
                            description = "Quaerat nostrum quae aut corrupti ratione quia voluptas.",
                            name = "Emery"
                        },
                        new
                        {
                            Id = 25,
                            description = "Eum quos harum laborum ullam harum aut.",
                            name = "Shanny"
                        },
                        new
                        {
                            Id = 26,
                            description = "Ut fugiat quos.",
                            name = "Raul"
                        },
                        new
                        {
                            Id = 27,
                            description = "Sapiente sint incidunt deserunt quidem sed.",
                            name = "Heather"
                        },
                        new
                        {
                            Id = 28,
                            description = "Suscipit qui porro inventore minus quod odio.",
                            name = "Agnes"
                        },
                        new
                        {
                            Id = 29,
                            description = "Itaque aliquid asperiores qui et quasi nam a quia.",
                            name = "Shad"
                        },
                        new
                        {
                            Id = 30,
                            description = "Eum magnam sunt cumque.",
                            name = "Robin"
                        },
                        new
                        {
                            Id = 31,
                            description = "Et sunt labore rerum.",
                            name = "Nola"
                        },
                        new
                        {
                            Id = 32,
                            description = "Sed reiciendis asperiores molestiae facilis.",
                            name = "Nakia"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "comment")
                        .WithOne("bookInteraction")
                        .HasForeignKey("QLSach.database.models.BookInteraction", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "parent")
                        .WithMany("childrents")
                        .HasForeignKey("parent_id");

                    b.Navigation("book");

                    b.Navigation("parent");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "Book")
                        .WithOne("photo")
                        .HasForeignKey("QLSach.database.models.Photo", "book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.HasOne("QLSach.dbContext.models.author", "author")
                        .WithOne("Book")
                        .HasForeignKey("QLSach.dbContext.models.Book", "author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("author");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Navigation("bookInteraction")
                        .IsRequired();

                    b.Navigation("childrents");
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("photo");
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
