// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSach.database;

#nullable disable

namespace QLSach.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241110083509_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("liked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<bool>("saved")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookInteractions");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.HasIndex("parent_id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 7,
                            UserId = 15,
                            content = "A dolorem recusandae suscipit quia repudiandae nulla aut."
                        },
                        new
                        {
                            Id = 2,
                            BookId = 23,
                            UserId = 13,
                            content = "Rerum ut aut distinctio quia."
                        },
                        new
                        {
                            Id = 3,
                            BookId = 10,
                            UserId = 6,
                            content = "Et doloremque eum qui."
                        },
                        new
                        {
                            Id = 4,
                            BookId = 16,
                            UserId = 4,
                            content = "Vel non sunt autem pariatur alias sit fuga."
                        },
                        new
                        {
                            Id = 5,
                            BookId = 21,
                            UserId = 16,
                            content = "Atque sit numquam."
                        },
                        new
                        {
                            Id = 6,
                            BookId = 10,
                            UserId = 4,
                            content = "Eos incidunt deleniti sit quidem non quia doloribus vel voluptates."
                        },
                        new
                        {
                            Id = 7,
                            BookId = 13,
                            UserId = 9,
                            content = "Reiciendis fugiat ut consequatur eaque et quo et esse."
                        },
                        new
                        {
                            Id = 8,
                            BookId = 9,
                            UserId = 14,
                            content = "Pariatur sapiente enim debitis libero."
                        },
                        new
                        {
                            Id = 9,
                            BookId = 14,
                            UserId = 6,
                            content = "Vero expedita qui placeat quo repudiandae doloribus tenetur dolor id."
                        },
                        new
                        {
                            Id = 10,
                            BookId = 17,
                            UserId = 2,
                            content = "Omnis eligendi voluptate quaerat sunt ad minus veritatis."
                        },
                        new
                        {
                            Id = 11,
                            BookId = 6,
                            UserId = 12,
                            content = "Sint temporibus accusamus est deserunt odit at ut."
                        },
                        new
                        {
                            Id = 12,
                            BookId = 4,
                            UserId = 16,
                            content = "Quis voluptatum sunt sit."
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            UserId = 6,
                            content = "Impedit error eum mollitia."
                        },
                        new
                        {
                            Id = 14,
                            BookId = 6,
                            UserId = 11,
                            content = "Dolor quas ut minima qui non quasi porro et velit."
                        },
                        new
                        {
                            Id = 15,
                            BookId = 16,
                            UserId = 2,
                            content = "Impedit fuga et."
                        },
                        new
                        {
                            Id = 16,
                            BookId = 27,
                            UserId = 7,
                            content = "Sed nobis blanditiis dolorem vel nesciunt."
                        },
                        new
                        {
                            Id = 17,
                            BookId = 23,
                            UserId = 11,
                            content = "Voluptatibus suscipit magnam ex numquam ea qui exercitationem.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 18,
                            BookId = 18,
                            UserId = 9,
                            content = "Quidem molestiae voluptas id.",
                            parent_id = 7
                        },
                        new
                        {
                            Id = 19,
                            BookId = 23,
                            UserId = 2,
                            content = "Ut nulla accusamus enim.",
                            parent_id = 4
                        },
                        new
                        {
                            Id = 20,
                            BookId = 11,
                            UserId = 4,
                            content = "Minima minima quidem qui deserunt.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 21,
                            BookId = 20,
                            UserId = 10,
                            content = "Dolores occaecati alias dolor aut.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 22,
                            BookId = 21,
                            UserId = 16,
                            content = "Et corporis dolorem inventore aut odit quo cupiditate et.",
                            parent_id = 3
                        },
                        new
                        {
                            Id = 23,
                            BookId = 4,
                            UserId = 12,
                            content = "Dignissimos autem reprehenderit vel.",
                            parent_id = 8
                        },
                        new
                        {
                            Id = 24,
                            BookId = 27,
                            UserId = 14,
                            content = "Aut consectetur officiis nobis aliquam quisquam in quibusdam.",
                            parent_id = 16
                        },
                        new
                        {
                            Id = 25,
                            BookId = 10,
                            UserId = 15,
                            content = "Ut itaque sed totam.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 26,
                            BookId = 13,
                            UserId = 3,
                            content = "Sapiente officiis est ducimus ut.",
                            parent_id = 12
                        },
                        new
                        {
                            Id = 27,
                            BookId = 16,
                            UserId = 14,
                            content = "Est minus suscipit eum in.",
                            parent_id = 15
                        },
                        new
                        {
                            Id = 28,
                            BookId = 24,
                            UserId = 9,
                            content = "Voluptatibus est voluptates.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 29,
                            BookId = 12,
                            UserId = 4,
                            content = "Minus consequuntur amet deleniti omnis ex.",
                            parent_id = 12
                        },
                        new
                        {
                            Id = 30,
                            BookId = 25,
                            UserId = 5,
                            content = "Corrupti tempore inventore aliquid quo omnis.",
                            parent_id = 15
                        },
                        new
                        {
                            Id = 31,
                            BookId = 25,
                            UserId = 11,
                            content = "Et possimus ut quibusdam omnis aut.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 32,
                            BookId = 20,
                            UserId = 4,
                            content = "Iure a dolorem illum vero ipsum.",
                            parent_id = 14
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "dolorem"
                        },
                        new
                        {
                            id = 2,
                            name = "ea"
                        },
                        new
                        {
                            id = 3,
                            name = "corporis"
                        },
                        new
                        {
                            id = 4,
                            name = "et"
                        },
                        new
                        {
                            id = 5,
                            name = "eos"
                        },
                        new
                        {
                            id = 6,
                            name = "id"
                        },
                        new
                        {
                            id = 7,
                            name = "eos"
                        },
                        new
                        {
                            id = 8,
                            name = "odio"
                        },
                        new
                        {
                            id = 9,
                            name = "ipsum"
                        },
                        new
                        {
                            id = 10,
                            name = "vitae"
                        },
                        new
                        {
                            id = 11,
                            name = "repellendus"
                        },
                        new
                        {
                            id = 12,
                            name = "qui"
                        },
                        new
                        {
                            id = 13,
                            name = "qui"
                        },
                        new
                        {
                            id = 14,
                            name = "numquam"
                        },
                        new
                        {
                            id = 15,
                            name = "quos"
                        },
                        new
                        {
                            id = 16,
                            name = "quos"
                        },
                        new
                        {
                            id = 17,
                            name = "quo"
                        },
                        new
                        {
                            id = 18,
                            name = "aut"
                        },
                        new
                        {
                            id = 19,
                            name = "quia"
                        },
                        new
                        {
                            id = 20,
                            name = "non"
                        },
                        new
                        {
                            id = 21,
                            name = "similique"
                        },
                        new
                        {
                            id = 22,
                            name = "mollitia"
                        },
                        new
                        {
                            id = 23,
                            name = "voluptates"
                        },
                        new
                        {
                            id = 24,
                            name = "sed"
                        },
                        new
                        {
                            id = 25,
                            name = "suscipit"
                        },
                        new
                        {
                            id = 26,
                            name = "at"
                        },
                        new
                        {
                            id = 27,
                            name = "molestias"
                        },
                        new
                        {
                            id = 28,
                            name = "et"
                        },
                        new
                        {
                            id = 29,
                            name = "ipsam"
                        },
                        new
                        {
                            id = 30,
                            name = "suscipit"
                        },
                        new
                        {
                            id = 31,
                            name = "dolores"
                        },
                        new
                        {
                            id = 32,
                            name = "veniam"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.Property<string>("path")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.HasKey("path");

                    b.HasIndex("book_id")
                        .IsUnique();

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            path = "1fake path",
                            book_id = 23
                        },
                        new
                        {
                            path = "2fake path",
                            book_id = 24
                        },
                        new
                        {
                            path = "3fake path",
                            book_id = 12
                        },
                        new
                        {
                            path = "4fake path",
                            book_id = 18
                        },
                        new
                        {
                            path = "5fake path",
                            book_id = 26
                        },
                        new
                        {
                            path = "6fake path",
                            book_id = 18
                        },
                        new
                        {
                            path = "7fake path",
                            book_id = 16
                        },
                        new
                        {
                            path = "8fake path",
                            book_id = 15
                        },
                        new
                        {
                            path = "9fake path",
                            book_id = 26
                        },
                        new
                        {
                            path = "10fake path",
                            book_id = 26
                        },
                        new
                        {
                            path = "11fake path",
                            book_id = 4
                        },
                        new
                        {
                            path = "12fake path",
                            book_id = 17
                        },
                        new
                        {
                            path = "13fake path",
                            book_id = 4
                        },
                        new
                        {
                            path = "14fake path",
                            book_id = 7
                        },
                        new
                        {
                            path = "15fake path",
                            book_id = 8
                        },
                        new
                        {
                            path = "16fake path",
                            book_id = 20
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("borrow_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expected_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("register_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("return_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Register");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 10,
                            Status = "Canceled",
                            UserId = 5,
                            register_at = new DateTime(2024, 11, 8, 0, 17, 43, 431, DateTimeKind.Local).AddTicks(2193)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 4,
                            Status = "Canceled",
                            UserId = 8,
                            register_at = new DateTime(2024, 11, 8, 21, 0, 5, 54, DateTimeKind.Local).AddTicks(3343)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 21,
                            Status = "Borrowed",
                            UserId = 2,
                            borrow_at = new DateTime(2024, 11, 6, 23, 45, 29, 196, DateTimeKind.Local).AddTicks(6124),
                            expected_at = new DateTime(2024, 11, 15, 5, 45, 56, 186, DateTimeKind.Local).AddTicks(1456),
                            register_at = new DateTime(2024, 11, 8, 5, 45, 56, 186, DateTimeKind.Local).AddTicks(1456)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 11,
                            Status = "Canceled",
                            UserId = 4,
                            register_at = new DateTime(2024, 11, 6, 0, 49, 58, 614, DateTimeKind.Local).AddTicks(2100)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            Status = "Borrowed",
                            UserId = 3,
                            borrow_at = new DateTime(2024, 11, 7, 7, 8, 11, 162, DateTimeKind.Local).AddTicks(1419),
                            expected_at = new DateTime(2024, 11, 13, 5, 17, 2, 673, DateTimeKind.Local).AddTicks(7676),
                            register_at = new DateTime(2024, 11, 6, 5, 17, 2, 673, DateTimeKind.Local).AddTicks(7676)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 27,
                            Status = "Borrowed",
                            UserId = 1,
                            borrow_at = new DateTime(2024, 11, 6, 7, 42, 52, 387, DateTimeKind.Local).AddTicks(3855),
                            expected_at = new DateTime(2024, 11, 11, 7, 58, 57, 159, DateTimeKind.Local).AddTicks(1290),
                            register_at = new DateTime(2024, 11, 4, 7, 58, 57, 159, DateTimeKind.Local).AddTicks(1290)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 25,
                            Status = "Completed",
                            UserId = 9,
                            borrow_at = new DateTime(2024, 11, 4, 16, 27, 17, 588, DateTimeKind.Local).AddTicks(1245),
                            expected_at = new DateTime(2024, 11, 11, 9, 29, 55, 510, DateTimeKind.Local).AddTicks(27),
                            register_at = new DateTime(2024, 11, 4, 9, 29, 55, 510, DateTimeKind.Local).AddTicks(27),
                            return_at = new DateTime(2024, 11, 8, 20, 30, 54, 89, DateTimeKind.Local).AddTicks(5207)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 17,
                            Status = "Pending",
                            UserId = 12,
                            expected_at = new DateTime(2024, 11, 15, 3, 48, 31, 993, DateTimeKind.Local).AddTicks(3760),
                            register_at = new DateTime(2024, 11, 8, 3, 48, 31, 993, DateTimeKind.Local).AddTicks(3760)
                        },
                        new
                        {
                            Id = 9,
                            BookId = 1,
                            Status = "Pending",
                            UserId = 12,
                            expected_at = new DateTime(2024, 11, 11, 1, 7, 10, 698, DateTimeKind.Local).AddTicks(728),
                            register_at = new DateTime(2024, 11, 4, 1, 7, 10, 698, DateTimeKind.Local).AddTicks(728)
                        },
                        new
                        {
                            Id = 10,
                            BookId = 15,
                            Status = "Borrowed",
                            UserId = 1,
                            borrow_at = new DateTime(2024, 11, 6, 0, 52, 17, 71, DateTimeKind.Local).AddTicks(4904),
                            expected_at = new DateTime(2024, 11, 16, 18, 5, 0, 214, DateTimeKind.Local).AddTicks(588),
                            register_at = new DateTime(2024, 11, 9, 18, 5, 0, 214, DateTimeKind.Local).AddTicks(588)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 24,
                            Status = "Completed",
                            UserId = 6,
                            borrow_at = new DateTime(2024, 11, 7, 18, 34, 45, 851, DateTimeKind.Local).AddTicks(1040),
                            expected_at = new DateTime(2024, 11, 12, 19, 52, 10, 123, DateTimeKind.Local).AddTicks(6329),
                            register_at = new DateTime(2024, 11, 5, 19, 52, 10, 123, DateTimeKind.Local).AddTicks(6329),
                            return_at = new DateTime(2024, 11, 8, 4, 14, 11, 313, DateTimeKind.Local).AddTicks(9238)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 14,
                            Status = "Canceled",
                            UserId = 2,
                            register_at = new DateTime(2024, 11, 7, 14, 1, 2, 927, DateTimeKind.Local).AddTicks(4258)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 10,
                            Status = "Canceled",
                            UserId = 15,
                            register_at = new DateTime(2024, 11, 5, 8, 44, 29, 764, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 10,
                            Status = "Canceled",
                            UserId = 3,
                            register_at = new DateTime(2024, 11, 4, 6, 52, 57, 669, DateTimeKind.Local).AddTicks(3167)
                        },
                        new
                        {
                            Id = 15,
                            BookId = 10,
                            Status = "Completed",
                            UserId = 2,
                            borrow_at = new DateTime(2024, 11, 9, 15, 18, 25, 894, DateTimeKind.Local).AddTicks(4629),
                            expected_at = new DateTime(2024, 11, 15, 6, 50, 6, 546, DateTimeKind.Local).AddTicks(7043),
                            register_at = new DateTime(2024, 11, 8, 6, 50, 6, 546, DateTimeKind.Local).AddTicks(7043),
                            return_at = new DateTime(2024, 11, 9, 6, 6, 23, 891, DateTimeKind.Local).AddTicks(9485)
                        },
                        new
                        {
                            Id = 16,
                            BookId = 17,
                            Status = "Borrowed",
                            UserId = 12,
                            borrow_at = new DateTime(2024, 11, 10, 12, 8, 12, 427, DateTimeKind.Local).AddTicks(8546),
                            expected_at = new DateTime(2024, 11, 14, 4, 4, 20, 873, DateTimeKind.Local).AddTicks(7029),
                            register_at = new DateTime(2024, 11, 7, 4, 4, 20, 873, DateTimeKind.Local).AddTicks(7029)
                        });
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "ex",
                            UserName = "General Daniel"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Sed delectus consequatur nulla autem voluptatem voluptatum maxime aut. Nisi corrupti est quia. Adipisci consequatur non consequatur omnis nihil. Dicta doloribus ad dolores consectetur quam similique. Suscipit enim blanditiis veritatis pariatur molestiae.",
                            UserName = "Jayda Stark"
                        },
                        new
                        {
                            Id = 3,
                            Password = "non",
                            UserName = "Don Hegmann"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Quis maiores reiciendis.\nQuo culpa in deserunt labore officia nulla voluptatem occaecati.\nReprehenderit ut sunt esse.",
                            UserName = "Sienna Mills"
                        },
                        new
                        {
                            Id = 5,
                            Password = "Nulla eum officiis sit voluptas qui ea.\nTempora et velit cupiditate.\nSequi odit ut non qui delectus voluptatem nam ut nobis.\nLaborum pariatur modi autem qui assumenda consequatur alias sint.\nRatione rerum ut et numquam est.",
                            UserName = "Chadrick Tromp"
                        },
                        new
                        {
                            Id = 6,
                            Password = "Quia ut eos voluptas illo nemo quo rerum et assumenda.\nQuia cum incidunt reiciendis est veniam dolore enim harum.\nIn dolor inventore distinctio et.\nEnim eligendi quaerat laudantium cumque hic porro soluta.\nOmnis dolorem et est incidunt quaerat occaecati nobis autem.",
                            UserName = "Tamara Jerde"
                        },
                        new
                        {
                            Id = 7,
                            Password = "Rerum voluptatem corporis. Maxime et vitae quis quos iure recusandae dolore molestiae unde. Quod ipsam officiis et tempore libero veniam perspiciatis soluta. Esse distinctio aliquid.",
                            UserName = "Krystina Runolfsdottir"
                        },
                        new
                        {
                            Id = 8,
                            Password = "Necessitatibus et totam recusandae. Modi rem placeat qui asperiores debitis et veniam impedit qui. Laudantium veritatis qui voluptatibus vel adipisci sint sint.",
                            UserName = "Nia Moore"
                        },
                        new
                        {
                            Id = 9,
                            Password = "In atque dolore doloremque. Nobis placeat ipsa magni. Laboriosam voluptatibus ut ex. Pariatur facilis autem error cum odit facilis nesciunt.",
                            UserName = "Tad Treutel"
                        },
                        new
                        {
                            Id = 10,
                            Password = "Tempora sunt voluptatem qui unde aut pariatur alias. Illo ab quia rerum est iste. Voluptas accusantium quibusdam animi saepe accusamus sequi.",
                            UserName = "Princess Reilly"
                        },
                        new
                        {
                            Id = 11,
                            Password = "Vitae mollitia tempora odio ut esse a deleniti. Voluptatem necessitatibus ut debitis nostrum aut nulla ex. Ab amet aperiam modi magni quo id ducimus. Voluptatem quos laudantium dolor quam.",
                            UserName = "Clementina Wehner"
                        },
                        new
                        {
                            Id = 12,
                            Password = "Laboriosam nihil neque dolore ut molestiae consequatur totam.\nPariatur dolor libero quo pariatur.\nQuibusdam delectus voluptates voluptates eum facilis nisi sed.\nVoluptatem aut enim minus.\nUt placeat deserunt quibusdam adipisci et facere eveniet.\nRerum animi eos omnis consectetur eos est.",
                            UserName = "Tristian Zieme"
                        },
                        new
                        {
                            Id = 13,
                            Password = "Rerum adipisci impedit dolor est autem reiciendis.",
                            UserName = "Breanne Wuckert"
                        },
                        new
                        {
                            Id = 14,
                            Password = "Ad nesciunt similique.\nAccusantium at voluptas optio doloremque perferendis placeat ut in.\nUt consequuntur omnis rerum voluptatem veniam quis sint.",
                            UserName = "Jamir Hoppe"
                        },
                        new
                        {
                            Id = 15,
                            Password = "Quo nulla ut tenetur eum quia fugiat. Ad doloremque aliquam accusamus. Rerum dolores consectetur accusantium ullam magni hic labore ut rerum. Et expedita vel.",
                            UserName = "Mertie Yost"
                        },
                        new
                        {
                            Id = 16,
                            Password = "Tempora eum iure.",
                            UserName = "Golda Gibson"
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("created_at"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("genre_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("quantity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("remaining")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("year_public")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("author_id")
                        .IsUnique();

                    b.HasIndex("genre_id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            author_id = 19,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(2674),
                            description = "Ea ut et non. Et quidem consequuntur dolores voluptate. Ipsam non eveniet assumenda aut est. Enim ab occaecati deleniti corporis eius est. Voluptatem voluptatem ullam mollitia alias dolor pariatur porro. Aut debitis sit unde.",
                            genre_id = 14,
                            name = "Eos cumque rerum dicta est qui expedita et earum porro.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(3197),
                            views = 0,
                            year_public = 2003
                        },
                        new
                        {
                            Id = 2,
                            author_id = 21,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(3934),
                            description = "Officia quasi dolores autem animi enim deserunt impedit eveniet voluptatem. Unde aliquam ut tempora nesciunt et quae. Qui iusto illum id repellat commodi optio.",
                            genre_id = 9,
                            name = "Expedita ut illo ipsam eaque quidem tempora.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4072),
                            views = 0,
                            year_public = 1958
                        },
                        new
                        {
                            Id = 3,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4084),
                            description = "Exercitationem hic neque cum qui dolores laboriosam accusamus perspiciatis quae. Nihil voluptates in et qui ut dolores veniam accusantium quia. Quos nihil qui ipsam et vitae accusamus enim nulla. Doloribus culpa enim voluptatem qui labore. Modi architecto dolorem temporibus. Nulla esse sed.",
                            genre_id = 20,
                            name = "Deserunt vero non placeat deleniti quis nihil voluptas.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4232),
                            views = 0,
                            year_public = 1971
                        },
                        new
                        {
                            Id = 4,
                            author_id = 31,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4243),
                            description = "Cumque dolor enim ut eos qui nihil neque. Quia dicta voluptatibus atque eum. Sed et odit ducimus aut modi iste libero debitis.",
                            genre_id = 7,
                            name = "In harum illum inventore dolorum ut.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4327),
                            views = 0,
                            year_public = 1996
                        },
                        new
                        {
                            Id = 5,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4338),
                            description = "Occaecati est ut illo nihil tempora itaque sit est pariatur. Ut nulla provident delectus quam ut. Sint ipsum ex. Impedit quam dolores facere quis occaecati doloribus reiciendis. Id illo tenetur distinctio.",
                            genre_id = 3,
                            name = "Excepturi numquam quis illo quae autem sed tempora.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4448),
                            views = 0,
                            year_public = 2022
                        },
                        new
                        {
                            Id = 6,
                            author_id = 10,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4459),
                            description = "Nam hic officia aliquam consequatur officiis magnam. Vitae vel alias. Placeat quaerat suscipit dolor. Vitae quo illo reprehenderit rerum quia voluptatibus dicta impedit voluptates. Unde natus in. Qui ipsa quia maiores nisi et odit error maiores.",
                            genre_id = 12,
                            name = "Illo quisquam aspernatur vitae et fugiat ea corporis libero et.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4575),
                            views = 0,
                            year_public = 1902
                        },
                        new
                        {
                            Id = 7,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4586),
                            description = "Fugiat asperiores ipsam sequi quasi. Molestias omnis eligendi pariatur commodi expedita delectus amet sit distinctio. Fugiat ut nemo. Eligendi minus porro quae. Perspiciatis aut dolores iure animi sit laudantium ut delectus officia. Sed cupiditate maxime eligendi illum voluptatem ab id autem.",
                            genre_id = 26,
                            name = "Qui distinctio vero eaque nihil.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4699),
                            views = 0,
                            year_public = 2019
                        },
                        new
                        {
                            Id = 8,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4712),
                            description = "Voluptatem quo consectetur aperiam consequatur ipsum unde animi animi. Occaecati temporibus qui laborum. Corrupti veritatis cum dolores eaque. Omnis voluptatem magnam sit magni eveniet unde aut. Architecto at laborum quidem vero quia soluta porro tempore.",
                            genre_id = 11,
                            name = "Eveniet sequi sit consequatur tempore.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4814),
                            views = 0,
                            year_public = 1948
                        },
                        new
                        {
                            Id = 9,
                            author_id = 22,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4825),
                            description = "Quo consequatur rerum dolor ut neque praesentium voluptatem eius. Iure suscipit tempora omnis commodi dignissimos id est. Veritatis dolorum aliquid neque quis et recusandae. Perferendis assumenda ea dolores eligendi qui eius ipsum optio. Qui doloremque et. Recusandae eos eos voluptatem explicabo fugit corrupti sequi recusandae.",
                            genre_id = 29,
                            name = "Qui cumque beatae quisquam et et ducimus molestiae.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4953),
                            views = 0,
                            year_public = 2017
                        },
                        new
                        {
                            Id = 10,
                            author_id = 25,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(4964),
                            description = "Nulla quo et reiciendis possimus ad similique officiis. Sit sapiente culpa ab sed dolor ducimus. Cum voluptas voluptatibus voluptatem doloribus nostrum. Omnis iste culpa corrupti.",
                            genre_id = 27,
                            name = "Dolorem minus eum pariatur consequatur rerum.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5054),
                            views = 0,
                            year_public = 1985
                        },
                        new
                        {
                            Id = 11,
                            author_id = 18,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5064),
                            description = "Sed eos reprehenderit recusandae repellendus autem. Vel nobis et sapiente tempore sed corrupti harum eos. Nobis impedit quia occaecati voluptas perferendis.",
                            genre_id = 20,
                            name = "Autem quidem ducimus pariatur est reiciendis.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5145),
                            views = 0,
                            year_public = 1996
                        },
                        new
                        {
                            Id = 12,
                            author_id = 23,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5156),
                            description = "Rerum cumque repellat. Autem sint vero neque ut sunt nobis sequi. Velit quam laborum dolores placeat debitis. Culpa cumque amet.",
                            genre_id = 6,
                            name = "Molestias sunt ea a voluptas aut.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5232),
                            views = 0,
                            year_public = 1991
                        },
                        new
                        {
                            Id = 13,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5242),
                            description = "Unde vel placeat. Dolorum inventore ratione saepe voluptatum voluptatibus. Tenetur odio accusamus quo iste ipsa. Doloremque quia dicta. Veniam sunt incidunt ea deserunt possimus est.",
                            genre_id = 29,
                            name = "Accusamus quo tenetur eos necessitatibus dolor.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5333),
                            views = 0,
                            year_public = 1917
                        },
                        new
                        {
                            Id = 14,
                            author_id = 15,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5343),
                            description = "Quod nihil expedita in deleniti molestiae expedita. Debitis voluptatem maiores voluptatem. Dolore ut itaque provident sunt alias porro.",
                            genre_id = 8,
                            name = "Non consequatur cupiditate nam.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5408),
                            views = 0,
                            year_public = 1985
                        },
                        new
                        {
                            Id = 15,
                            author_id = 1,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5418),
                            description = "Maiores quia minus animi et quas vero ex. Totam nobis repellendus. Quaerat vitae animi tempora autem minus officia vitae. Aut magni sit sed a ut fuga. Et tenetur soluta impedit perspiciatis fuga. Alias ullam est est deleniti quo quod voluptatem odio aut.",
                            genre_id = 23,
                            name = "Facere neque reprehenderit aut sed est sit id.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5539),
                            views = 0,
                            year_public = 1981
                        },
                        new
                        {
                            Id = 16,
                            author_id = 6,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5549),
                            description = "Aliquam reiciendis qui veniam recusandae est voluptatem. Error natus omnis et quia maiores temporibus est consequatur beatae. Commodi error est temporibus et. Accusantium dolore provident.",
                            genre_id = 4,
                            name = "Excepturi at iusto asperiores expedita dolore non.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5643),
                            views = 0,
                            year_public = 2014
                        },
                        new
                        {
                            Id = 17,
                            author_id = 14,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5653),
                            description = "Nihil vel exercitationem repudiandae et tempora aliquam quaerat. Corrupti sunt quibusdam aliquam. Earum enim asperiores.",
                            genre_id = 19,
                            name = "Ipsa atque quis quam.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5714),
                            views = 0,
                            year_public = 1940
                        },
                        new
                        {
                            Id = 18,
                            author_id = 22,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5731),
                            description = "Ab dolorum dolor deleniti pariatur ipsa quam sit neque. Sed rerum sed ut et nemo et. Quia dignissimos placeat omnis fugiat quibusdam iusto voluptatem et ea. Autem saepe excepturi quo voluptatibus eos et nihil vitae.",
                            genre_id = 31,
                            name = "Cumque est et exercitationem illo vel porro culpa nisi.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5831),
                            views = 0,
                            year_public = 2023
                        },
                        new
                        {
                            Id = 19,
                            author_id = 17,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5842),
                            description = "Aut amet sit veniam eveniet. Magnam minima eius est numquam sint qui rem veritatis iste. Dolor voluptatibus neque. Dolores ea sunt dolorum facilis rerum debitis a eveniet. Dolores optio fuga est quaerat quisquam et molestiae.",
                            genre_id = 19,
                            name = "Exercitationem sunt ut aut tempora quo reprehenderit.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5948),
                            views = 0,
                            year_public = 1940
                        },
                        new
                        {
                            Id = 20,
                            author_id = 31,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(5958),
                            description = "Non saepe praesentium dolorem magnam. Quibusdam aut dolor molestias nam aspernatur. Debitis culpa omnis libero qui molestiae. Ullam ipsum qui sunt nihil aliquid id velit ipsa nobis.",
                            genre_id = 3,
                            name = "Rerum quibusdam totam exercitationem autem facilis doloribus reprehenderit.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6050),
                            views = 0,
                            year_public = 1985
                        },
                        new
                        {
                            Id = 21,
                            author_id = 19,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6060),
                            description = "Nulla mollitia perferendis non. Facilis id qui vel voluptatem. Consequatur libero velit reprehenderit quisquam minima adipisci saepe. In possimus ut doloribus quae et quo quidem.",
                            genre_id = 10,
                            name = "Quos praesentium voluptatem sit vero architecto facilis.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6144),
                            views = 0,
                            year_public = 1968
                        },
                        new
                        {
                            Id = 22,
                            author_id = 22,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6158),
                            description = "Ut deserunt incidunt nam tempora dolorem. Mollitia minima provident. Reprehenderit aut dolores. Error eum ut.",
                            genre_id = 14,
                            name = "Quia eum illo.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6220),
                            views = 0,
                            year_public = 1931
                        },
                        new
                        {
                            Id = 23,
                            author_id = 1,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6230),
                            description = "Et maiores esse. Rerum dolore quibusdam cum eos voluptates aut ab sed tenetur. Suscipit reprehenderit dolores dolore temporibus aut fuga et ducimus.",
                            genre_id = 6,
                            name = "Dolor atque sed omnis est inventore laborum placeat.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6310),
                            views = 0,
                            year_public = 1953
                        },
                        new
                        {
                            Id = 24,
                            author_id = 12,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6320),
                            description = "Sit voluptas voluptatem magnam. Est dolorum laudantium. Velit maxime qui ipsum temporibus praesentium animi.",
                            genre_id = 31,
                            name = "Qui quasi amet voluptatum commodi molestias.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6384),
                            views = 0,
                            year_public = 1922
                        },
                        new
                        {
                            Id = 25,
                            author_id = 17,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6395),
                            description = "Non repellat non eum sed. Deserunt occaecati blanditiis. Magni facilis culpa sit et aspernatur. Culpa ipsam voluptas blanditiis id quia. Voluptatum accusamus molestiae perspiciatis repudiandae repellendus expedita ullam omnis.",
                            genre_id = 8,
                            name = "Animi unde et et velit nulla.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6490),
                            views = 0,
                            year_public = 1926
                        },
                        new
                        {
                            Id = 26,
                            author_id = 20,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6500),
                            description = "Ducimus optio quia mollitia vel nemo est. Et non reprehenderit minus sint. Optio et eligendi impedit ipsum dolor autem tenetur doloremque. Sit animi itaque est sint voluptatem dicta ab ut laudantium. Consectetur sit delectus.",
                            genre_id = 25,
                            name = "Alias ut saepe voluptatem consequatur aspernatur.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6607),
                            views = 0,
                            year_public = 1933
                        },
                        new
                        {
                            Id = 27,
                            author_id = 24,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6617),
                            description = "Sed in natus aliquid quis rerum iusto iure quia. Animi saepe nisi rerum. Quis minus sequi est quasi. Beatae non maxime aperiam. Explicabo sit mollitia fugiat quae.",
                            genre_id = 5,
                            name = "Ut laudantium quaerat.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6701),
                            views = 0,
                            year_public = 1916
                        },
                        new
                        {
                            Id = 28,
                            author_id = 26,
                            created_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6711),
                            description = "Culpa qui natus. Ab neque omnis qui. Dolores nihil corporis ea. Voluptatem nostrum velit esse. Inventore similique aut aut eius.",
                            genre_id = 14,
                            name = "Quo voluptas facere omnis.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 10, 15, 35, 9, 614, DateTimeKind.Local).AddTicks(6791),
                            views = 0,
                            year_public = 1961
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Quas distinctio aut ex quas.",
                            name = "Alexis"
                        },
                        new
                        {
                            Id = 2,
                            description = "Laboriosam molestias quis et dicta incidunt voluptas repellendus.",
                            name = "Jamaal"
                        },
                        new
                        {
                            Id = 3,
                            description = "Quibusdam a molestiae autem aut distinctio exercitationem et in.",
                            name = "Vicky"
                        },
                        new
                        {
                            Id = 4,
                            description = "Quisquam perspiciatis repellat ea sed sunt.",
                            name = "Keely"
                        },
                        new
                        {
                            Id = 5,
                            description = "Voluptatem enim non id nam enim praesentium et.",
                            name = "Major"
                        },
                        new
                        {
                            Id = 6,
                            description = "Doloremque aut aut amet ut ut.",
                            name = "Randi"
                        },
                        new
                        {
                            Id = 7,
                            description = "Doloremque expedita dignissimos nisi quaerat nihil nostrum voluptas.",
                            name = "Duane"
                        },
                        new
                        {
                            Id = 8,
                            description = "Molestias natus quisquam.",
                            name = "June"
                        },
                        new
                        {
                            Id = 9,
                            description = "Harum distinctio hic et maiores qui cum velit.",
                            name = "Roslyn"
                        },
                        new
                        {
                            Id = 10,
                            description = "Vitae fugiat modi aut id eos maiores autem.",
                            name = "Jacey"
                        },
                        new
                        {
                            Id = 11,
                            description = "Magni a eum quia omnis in.",
                            name = "Don"
                        },
                        new
                        {
                            Id = 12,
                            description = "Modi et unde repellat reiciendis at alias quae.",
                            name = "Domenic"
                        },
                        new
                        {
                            Id = 13,
                            description = "Cumque vel et aut nulla.",
                            name = "Jerrell"
                        },
                        new
                        {
                            Id = 14,
                            description = "Mollitia architecto atque et est sint sed assumenda modi.",
                            name = "Enoch"
                        },
                        new
                        {
                            Id = 15,
                            description = "Perspiciatis ullam nisi.",
                            name = "Ressie"
                        },
                        new
                        {
                            Id = 16,
                            description = "Vel qui assumenda dolor ea laudantium velit impedit similique.",
                            name = "Madelyn"
                        },
                        new
                        {
                            Id = 17,
                            description = "Animi rerum dolorum.",
                            name = "Lera"
                        },
                        new
                        {
                            Id = 18,
                            description = "Et quo et et veritatis repellat enim nihil neque.",
                            name = "Charley"
                        },
                        new
                        {
                            Id = 19,
                            description = "Dolores quis asperiores voluptatem.",
                            name = "Freddy"
                        },
                        new
                        {
                            Id = 20,
                            description = "Soluta neque et nostrum.",
                            name = "Alvis"
                        },
                        new
                        {
                            Id = 21,
                            description = "Eos velit odit aut labore nostrum exercitationem vero.",
                            name = "Gillian"
                        },
                        new
                        {
                            Id = 22,
                            description = "Enim recusandae praesentium sit amet sequi eos quos quidem repudiandae.",
                            name = "Fidel"
                        },
                        new
                        {
                            Id = 23,
                            description = "Qui recusandae consequatur velit rerum quo repudiandae accusantium dolores.",
                            name = "Brown"
                        },
                        new
                        {
                            Id = 24,
                            description = "Consectetur esse voluptatem.",
                            name = "Skyla"
                        },
                        new
                        {
                            Id = 25,
                            description = "Quasi ipsa aut eius voluptas sint quaerat quia dicta.",
                            name = "Modesta"
                        },
                        new
                        {
                            Id = 26,
                            description = "Sunt possimus repellat.",
                            name = "Elmore"
                        },
                        new
                        {
                            Id = 27,
                            description = "Velit hic dignissimos.",
                            name = "Xavier"
                        },
                        new
                        {
                            Id = 28,
                            description = "Voluptatum inventore omnis possimus magnam et itaque provident rerum.",
                            name = "Gilda"
                        },
                        new
                        {
                            Id = 29,
                            description = "Laborum nam dolores hic cumque explicabo qui vero quidem quasi.",
                            name = "Milford"
                        },
                        new
                        {
                            Id = 30,
                            description = "Omnis similique eum at minus odit occaecati incidunt rerum.",
                            name = "Heber"
                        },
                        new
                        {
                            Id = 31,
                            description = "Sit dolor illum consectetur quis error enim et a quia.",
                            name = "Bernard"
                        },
                        new
                        {
                            Id = 32,
                            description = "Qui sunt beatae quia velit vitae eaque necessitatibus cumque praesentium.",
                            name = "Raheem"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "comment")
                        .WithOne("bookInteraction")
                        .HasForeignKey("QLSach.database.models.BookInteraction", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "parent")
                        .WithMany("childrents")
                        .HasForeignKey("parent_id");

                    b.Navigation("book");

                    b.Navigation("parent");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "Book")
                        .WithOne("photo")
                        .HasForeignKey("QLSach.database.models.Photo", "book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLSach.database.models.Register", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.HasOne("QLSach.dbContext.models.author", "author")
                        .WithOne("Book")
                        .HasForeignKey("QLSach.dbContext.models.Book", "author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("author");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Navigation("bookInteraction")
                        .IsRequired();

                    b.Navigation("childrents");
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("photo");
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
