// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSach.database;

#nullable disable

namespace QLSach.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241112025639_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("liked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<bool>("saved")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookInteractions");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.HasIndex("parent_id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 20,
                            UserId = 16,
                            content = "Qui dolor saepe sed omnis ad beatae et enim."
                        },
                        new
                        {
                            Id = 2,
                            BookId = 8,
                            UserId = 12,
                            content = "Et enim voluptates quo itaque."
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            UserId = 16,
                            content = "Saepe qui maiores et ea molestiae."
                        },
                        new
                        {
                            Id = 4,
                            BookId = 6,
                            UserId = 4,
                            content = "Quas est vitae error id harum assumenda voluptatem."
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            UserId = 7,
                            content = "Quibusdam aperiam aut aperiam magni eligendi."
                        },
                        new
                        {
                            Id = 6,
                            BookId = 18,
                            UserId = 14,
                            content = "Alias magni sapiente velit."
                        },
                        new
                        {
                            Id = 7,
                            BookId = 10,
                            UserId = 9,
                            content = "Voluptatem ipsum voluptate nihil soluta aut architecto sed."
                        },
                        new
                        {
                            Id = 8,
                            BookId = 24,
                            UserId = 16,
                            content = "Veritatis dolor repellat magnam aut repellendus voluptatem voluptatibus eligendi."
                        },
                        new
                        {
                            Id = 9,
                            BookId = 18,
                            UserId = 15,
                            content = "Aperiam et recusandae ipsum ad recusandae est omnis."
                        },
                        new
                        {
                            Id = 10,
                            BookId = 21,
                            UserId = 5,
                            content = "Ipsam aut ipsa vero dignissimos dolores perferendis."
                        },
                        new
                        {
                            Id = 11,
                            BookId = 27,
                            UserId = 2,
                            content = "Nihil recusandae error."
                        },
                        new
                        {
                            Id = 12,
                            BookId = 20,
                            UserId = 11,
                            content = "Dolor rem dolore et eos velit."
                        },
                        new
                        {
                            Id = 13,
                            BookId = 8,
                            UserId = 4,
                            content = "Doloribus ad et sed."
                        },
                        new
                        {
                            Id = 14,
                            BookId = 18,
                            UserId = 5,
                            content = "Nihil omnis nostrum et exercitationem."
                        },
                        new
                        {
                            Id = 15,
                            BookId = 20,
                            UserId = 10,
                            content = "Atque sunt id quis id."
                        },
                        new
                        {
                            Id = 16,
                            BookId = 5,
                            UserId = 9,
                            content = "Odit ex labore reprehenderit alias."
                        },
                        new
                        {
                            Id = 17,
                            BookId = 27,
                            UserId = 5,
                            content = "Laudantium consequatur velit tempora ut ea perferendis molestiae.",
                            parent_id = 8
                        },
                        new
                        {
                            Id = 18,
                            BookId = 27,
                            UserId = 6,
                            content = "Facere eum qui aperiam iusto voluptatibus.",
                            parent_id = 7
                        },
                        new
                        {
                            Id = 19,
                            BookId = 16,
                            UserId = 11,
                            content = "Ea error et vitae omnis a asperiores iure consequatur.",
                            parent_id = 16
                        },
                        new
                        {
                            Id = 20,
                            BookId = 26,
                            UserId = 15,
                            content = "Ad quisquam quibusdam.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 21,
                            BookId = 16,
                            UserId = 16,
                            content = "Quo quia est voluptates aspernatur facilis quidem velit ut sit.",
                            parent_id = 3
                        },
                        new
                        {
                            Id = 22,
                            BookId = 24,
                            UserId = 8,
                            content = "Eaque accusamus totam quibusdam.",
                            parent_id = 16
                        },
                        new
                        {
                            Id = 23,
                            BookId = 11,
                            UserId = 1,
                            content = "Illum cumque assumenda assumenda est ipsum qui expedita.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 24,
                            BookId = 9,
                            UserId = 13,
                            content = "Aliquid magnam iste similique voluptatibus vel.",
                            parent_id = 12
                        },
                        new
                        {
                            Id = 25,
                            BookId = 13,
                            UserId = 13,
                            content = "Non velit maxime rerum eos voluptatum sed sequi autem ut.",
                            parent_id = 7
                        },
                        new
                        {
                            Id = 26,
                            BookId = 8,
                            UserId = 7,
                            content = "Commodi quod tenetur expedita modi accusantium beatae dolorem sequi natus.",
                            parent_id = 12
                        },
                        new
                        {
                            Id = 27,
                            BookId = 19,
                            UserId = 10,
                            content = "Expedita exercitationem optio est adipisci nihil.",
                            parent_id = 14
                        },
                        new
                        {
                            Id = 28,
                            BookId = 14,
                            UserId = 7,
                            content = "Temporibus reprehenderit quisquam nostrum.",
                            parent_id = 7
                        },
                        new
                        {
                            Id = 29,
                            BookId = 16,
                            UserId = 9,
                            content = "Error natus assumenda veniam iste.",
                            parent_id = 7
                        },
                        new
                        {
                            Id = 30,
                            BookId = 26,
                            UserId = 15,
                            content = "Consequuntur modi quibusdam doloremque autem sit.",
                            parent_id = 15
                        },
                        new
                        {
                            Id = 31,
                            BookId = 18,
                            UserId = 4,
                            content = "Libero eligendi id error nulla doloribus minus quia.",
                            parent_id = 1
                        },
                        new
                        {
                            Id = 32,
                            BookId = 22,
                            UserId = 6,
                            content = "Nobis corporis autem iusto.",
                            parent_id = 7
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "praesentium"
                        },
                        new
                        {
                            id = 2,
                            name = "occaecati"
                        },
                        new
                        {
                            id = 3,
                            name = "sapiente"
                        },
                        new
                        {
                            id = 4,
                            name = "libero"
                        },
                        new
                        {
                            id = 5,
                            name = "dolor"
                        },
                        new
                        {
                            id = 6,
                            name = "ipsum"
                        },
                        new
                        {
                            id = 7,
                            name = "aperiam"
                        },
                        new
                        {
                            id = 8,
                            name = "cum"
                        },
                        new
                        {
                            id = 9,
                            name = "ea"
                        },
                        new
                        {
                            id = 10,
                            name = "exercitationem"
                        },
                        new
                        {
                            id = 11,
                            name = "quam"
                        },
                        new
                        {
                            id = 12,
                            name = "quo"
                        },
                        new
                        {
                            id = 13,
                            name = "rerum"
                        },
                        new
                        {
                            id = 14,
                            name = "a"
                        },
                        new
                        {
                            id = 15,
                            name = "consequuntur"
                        },
                        new
                        {
                            id = 16,
                            name = "vitae"
                        },
                        new
                        {
                            id = 17,
                            name = "vel"
                        },
                        new
                        {
                            id = 18,
                            name = "provident"
                        },
                        new
                        {
                            id = 19,
                            name = "quibusdam"
                        },
                        new
                        {
                            id = 20,
                            name = "soluta"
                        },
                        new
                        {
                            id = 21,
                            name = "illum"
                        },
                        new
                        {
                            id = 22,
                            name = "officiis"
                        },
                        new
                        {
                            id = 23,
                            name = "nemo"
                        },
                        new
                        {
                            id = 24,
                            name = "adipisci"
                        },
                        new
                        {
                            id = 25,
                            name = "doloremque"
                        },
                        new
                        {
                            id = 26,
                            name = "eveniet"
                        },
                        new
                        {
                            id = 27,
                            name = "aperiam"
                        },
                        new
                        {
                            id = 28,
                            name = "sed"
                        },
                        new
                        {
                            id = 29,
                            name = "non"
                        },
                        new
                        {
                            id = 30,
                            name = "possimus"
                        },
                        new
                        {
                            id = 31,
                            name = "ut"
                        },
                        new
                        {
                            id = 32,
                            name = "quaerat"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.Property<string>("path")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.HasKey("path");

                    b.HasIndex("book_id")
                        .IsUnique();

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            path = "1fake path",
                            book_id = 25
                        },
                        new
                        {
                            path = "2fake path",
                            book_id = 18
                        },
                        new
                        {
                            path = "3fake path",
                            book_id = 27
                        },
                        new
                        {
                            path = "4fake path",
                            book_id = 16
                        },
                        new
                        {
                            path = "5fake path",
                            book_id = 11
                        },
                        new
                        {
                            path = "6fake path",
                            book_id = 11
                        },
                        new
                        {
                            path = "7fake path",
                            book_id = 15
                        },
                        new
                        {
                            path = "8fake path",
                            book_id = 28
                        },
                        new
                        {
                            path = "9fake path",
                            book_id = 23
                        },
                        new
                        {
                            path = "10fake path",
                            book_id = 20
                        },
                        new
                        {
                            path = "11fake path",
                            book_id = 28
                        },
                        new
                        {
                            path = "12fake path",
                            book_id = 2
                        },
                        new
                        {
                            path = "13fake path",
                            book_id = 28
                        },
                        new
                        {
                            path = "14fake path",
                            book_id = 5
                        },
                        new
                        {
                            path = "15fake path",
                            book_id = 25
                        },
                        new
                        {
                            path = "16fake path",
                            book_id = 22
                        });
                });

            modelBuilder.Entity("QLSach.database.models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("borrow_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expected_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("register_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("return_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Register");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 16,
                            Status = "Completed",
                            UserId = 16,
                            borrow_at = new DateTime(2024, 11, 11, 22, 38, 13, 711, DateTimeKind.Local).AddTicks(7868),
                            expected_at = new DateTime(2024, 11, 12, 13, 57, 56, 831, DateTimeKind.Local).AddTicks(5482),
                            register_at = new DateTime(2024, 11, 5, 13, 57, 56, 831, DateTimeKind.Local).AddTicks(5482),
                            return_at = new DateTime(2024, 11, 11, 5, 27, 22, 441, DateTimeKind.Local).AddTicks(1391)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 18,
                            Status = "Canceled",
                            UserId = 7,
                            register_at = new DateTime(2024, 11, 12, 3, 57, 2, 326, DateTimeKind.Local).AddTicks(1673)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 10,
                            Status = "Borrowed",
                            UserId = 16,
                            borrow_at = new DateTime(2024, 11, 8, 5, 20, 29, 740, DateTimeKind.Local).AddTicks(8247),
                            expected_at = new DateTime(2024, 11, 15, 13, 33, 25, 761, DateTimeKind.Local).AddTicks(6371),
                            register_at = new DateTime(2024, 11, 8, 13, 33, 25, 761, DateTimeKind.Local).AddTicks(6371)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 9,
                            Status = "Borrowed",
                            UserId = 3,
                            borrow_at = new DateTime(2024, 11, 8, 13, 35, 23, 267, DateTimeKind.Local).AddTicks(1705),
                            expected_at = new DateTime(2024, 11, 13, 3, 55, 11, 455, DateTimeKind.Local).AddTicks(5149),
                            register_at = new DateTime(2024, 11, 6, 3, 55, 11, 455, DateTimeKind.Local).AddTicks(5149)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 23,
                            Status = "Borrowed",
                            UserId = 16,
                            borrow_at = new DateTime(2024, 11, 10, 9, 16, 45, 908, DateTimeKind.Local).AddTicks(947),
                            expected_at = new DateTime(2024, 11, 16, 0, 54, 31, 546, DateTimeKind.Local).AddTicks(9773),
                            register_at = new DateTime(2024, 11, 9, 0, 54, 31, 546, DateTimeKind.Local).AddTicks(9773)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 8,
                            Status = "Borrowed",
                            UserId = 13,
                            borrow_at = new DateTime(2024, 11, 10, 12, 43, 38, 750, DateTimeKind.Local).AddTicks(4333),
                            expected_at = new DateTime(2024, 11, 12, 13, 57, 1, 496, DateTimeKind.Local).AddTicks(6019),
                            register_at = new DateTime(2024, 11, 5, 13, 57, 1, 496, DateTimeKind.Local).AddTicks(6019)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 21,
                            Status = "Completed",
                            UserId = 13,
                            borrow_at = new DateTime(2024, 11, 12, 9, 53, 13, 889, DateTimeKind.Local).AddTicks(7210),
                            expected_at = new DateTime(2024, 11, 13, 0, 51, 28, 522, DateTimeKind.Local).AddTicks(7749),
                            register_at = new DateTime(2024, 11, 6, 0, 51, 28, 522, DateTimeKind.Local).AddTicks(7749),
                            return_at = new DateTime(2024, 11, 10, 23, 8, 14, 248, DateTimeKind.Local).AddTicks(2417)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 14,
                            Status = "Borrowed",
                            UserId = 1,
                            borrow_at = new DateTime(2024, 11, 11, 5, 17, 15, 833, DateTimeKind.Local).AddTicks(4967),
                            expected_at = new DateTime(2024, 11, 17, 13, 20, 53, 431, DateTimeKind.Local).AddTicks(5267),
                            register_at = new DateTime(2024, 11, 10, 13, 20, 53, 431, DateTimeKind.Local).AddTicks(5267)
                        },
                        new
                        {
                            Id = 9,
                            BookId = 24,
                            Status = "Completed",
                            UserId = 6,
                            borrow_at = new DateTime(2024, 11, 10, 9, 42, 36, 905, DateTimeKind.Local).AddTicks(544),
                            expected_at = new DateTime(2024, 11, 18, 20, 51, 4, 708, DateTimeKind.Local).AddTicks(9380),
                            register_at = new DateTime(2024, 11, 11, 20, 51, 4, 708, DateTimeKind.Local).AddTicks(9380),
                            return_at = new DateTime(2024, 11, 11, 11, 39, 17, 800, DateTimeKind.Local).AddTicks(6170)
                        },
                        new
                        {
                            Id = 10,
                            BookId = 14,
                            Status = "Completed",
                            UserId = 9,
                            borrow_at = new DateTime(2024, 11, 9, 1, 16, 34, 665, DateTimeKind.Local).AddTicks(9713),
                            expected_at = new DateTime(2024, 11, 15, 11, 12, 5, 1, DateTimeKind.Local).AddTicks(5292),
                            register_at = new DateTime(2024, 11, 8, 11, 12, 5, 1, DateTimeKind.Local).AddTicks(5292),
                            return_at = new DateTime(2024, 11, 11, 14, 28, 2, 521, DateTimeKind.Local).AddTicks(3035)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 24,
                            Status = "Canceled",
                            UserId = 1,
                            register_at = new DateTime(2024, 11, 11, 6, 45, 38, 75, DateTimeKind.Local).AddTicks(6890)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            Status = "Completed",
                            UserId = 16,
                            borrow_at = new DateTime(2024, 11, 11, 11, 3, 39, 668, DateTimeKind.Local).AddTicks(4372),
                            expected_at = new DateTime(2024, 11, 13, 22, 49, 7, 790, DateTimeKind.Local).AddTicks(9402),
                            register_at = new DateTime(2024, 11, 6, 22, 49, 7, 790, DateTimeKind.Local).AddTicks(9402),
                            return_at = new DateTime(2024, 11, 10, 14, 14, 5, 64, DateTimeKind.Local).AddTicks(8727)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 14,
                            Status = "Canceled",
                            UserId = 1,
                            register_at = new DateTime(2024, 11, 11, 14, 22, 43, 185, DateTimeKind.Local).AddTicks(4932)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 22,
                            Status = "Completed",
                            UserId = 8,
                            borrow_at = new DateTime(2024, 11, 8, 14, 41, 56, 648, DateTimeKind.Local).AddTicks(2382),
                            expected_at = new DateTime(2024, 11, 19, 4, 6, 7, 218, DateTimeKind.Local).AddTicks(658),
                            register_at = new DateTime(2024, 11, 12, 4, 6, 7, 218, DateTimeKind.Local).AddTicks(658),
                            return_at = new DateTime(2024, 11, 9, 10, 27, 44, 796, DateTimeKind.Local).AddTicks(3623)
                        },
                        new
                        {
                            Id = 15,
                            BookId = 18,
                            Status = "Completed",
                            UserId = 10,
                            borrow_at = new DateTime(2024, 11, 11, 9, 8, 11, 131, DateTimeKind.Local).AddTicks(7630),
                            expected_at = new DateTime(2024, 11, 12, 11, 26, 57, 344, DateTimeKind.Local).AddTicks(5217),
                            register_at = new DateTime(2024, 11, 5, 11, 26, 57, 344, DateTimeKind.Local).AddTicks(5217),
                            return_at = new DateTime(2024, 11, 11, 2, 23, 28, 711, DateTimeKind.Local).AddTicks(2236)
                        },
                        new
                        {
                            Id = 16,
                            BookId = 9,
                            Status = "Canceled",
                            UserId = 4,
                            register_at = new DateTime(2024, 11, 9, 2, 15, 59, 675, DateTimeKind.Local).AddTicks(6422)
                        });
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Eaque magnam in voluptates quae minus enim repellat aspernatur quae.",
                            UserName = "Thad Rohan"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Maiores in mollitia quis.\nQuia ut atque asperiores.\nSequi sunt illo illo ullam delectus velit qui molestiae.\nAsperiores quas totam ut sit quia nobis consequatur.",
                            UserName = "Tanya MacGyver"
                        },
                        new
                        {
                            Id = 3,
                            Password = "sint",
                            UserName = "Madaline Schumm"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Repellat quam animi dolores.",
                            UserName = "Magali Ziemann"
                        },
                        new
                        {
                            Id = 5,
                            Password = "Possimus fuga et aut sint cumque.\nNihil officiis est facere animi.\nVel quis aut consequatur quas et.\nDistinctio sed dolores aliquid sunt voluptatibus minus eos.",
                            UserName = "Winston Feeney"
                        },
                        new
                        {
                            Id = 6,
                            Password = "Id voluptatem est modi facilis dolores maxime sapiente sunt. Dicta officiis numquam aliquam suscipit veniam. Excepturi qui suscipit voluptatum. Eius blanditiis sint aut ex blanditiis omnis voluptatem molestiae sed.",
                            UserName = "Nya Herzog"
                        },
                        new
                        {
                            Id = 7,
                            Password = "Ut qui non dolor officia. Non voluptate eveniet. Libero consequatur aperiam velit porro eligendi occaecati eum at sit.",
                            UserName = "Serenity Kunze"
                        },
                        new
                        {
                            Id = 8,
                            Password = "Ab asperiores doloremque sit provident sit placeat nemo.",
                            UserName = "Izabella Schulist"
                        },
                        new
                        {
                            Id = 9,
                            Password = "Et placeat aut.\nIusto alias eum odit id temporibus.\nVoluptate tempora temporibus eum incidunt qui sapiente error consectetur doloribus.",
                            UserName = "Tavares Monahan"
                        },
                        new
                        {
                            Id = 10,
                            Password = "Doloribus velit quaerat facere deleniti reiciendis recusandae libero. Repellendus rem veniam totam distinctio odit vel vero sunt recusandae. Qui qui molestiae.",
                            UserName = "Nils Bashirian"
                        },
                        new
                        {
                            Id = 11,
                            Password = "omnis",
                            UserName = "Gudrun Wilkinson"
                        },
                        new
                        {
                            Id = 12,
                            Password = "Occaecati nesciunt accusantium dolor et nulla maiores ex.",
                            UserName = "Eleonore Hyatt"
                        },
                        new
                        {
                            Id = 13,
                            Password = "Commodi sint nam molestiae accusamus quod architecto.",
                            UserName = "Jaida Stanton"
                        },
                        new
                        {
                            Id = 14,
                            Password = "Dolorem totam dolores architecto.",
                            UserName = "Javier Connelly"
                        },
                        new
                        {
                            Id = 15,
                            Password = "Amet et nobis voluptas consequatur atque accusamus.\nVoluptatem adipisci eveniet quam a.\nDelectus ad incidunt aperiam.",
                            UserName = "Justyn Ferry"
                        },
                        new
                        {
                            Id = 16,
                            Password = "Nobis ipsum quam consequuntur voluptate aut alias.",
                            UserName = "Roscoe McKenzie"
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("created_at"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("genre_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("quantity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("remaining")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("year_public")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("author_id")
                        .IsUnique();

                    b.HasIndex("genre_id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            author_id = 4,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(582),
                            description = "Ut cum reprehenderit consequatur voluptatem dicta. Architecto voluptatum adipisci occaecati id. Nesciunt illum ut non ut possimus et suscipit natus. Earum laudantium quae odit esse illum dolor harum molestiae. Officia dolores delectus veritatis ea dolorem ducimus amet.",
                            genre_id = 30,
                            name = "Ratione aut facere omnis minima voluptatem.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(1107),
                            views = 0,
                            year_public = 1987
                        },
                        new
                        {
                            Id = 2,
                            author_id = 4,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(1883),
                            description = "Et velit eveniet officia voluptatem. Quisquam in ut quisquam quis qui error a. Iusto eum quisquam. Eveniet est dolor cupiditate omnis cumque eos ipsam placeat nihil. Quis asperiores non blanditiis.",
                            genre_id = 27,
                            name = "Magnam tempora quidem consectetur reprehenderit aut.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2045),
                            views = 0,
                            year_public = 1910
                        },
                        new
                        {
                            Id = 3,
                            author_id = 23,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2058),
                            description = "Earum sed maiores et et sed. Et necessitatibus necessitatibus consequatur nisi. Impedit impedit et et dolore optio. Placeat et excepturi sint error voluptatum sint nulla aspernatur. Magni dolore ad non sit repudiandae illo.",
                            genre_id = 8,
                            name = "Ut culpa rerum possimus explicabo voluptas.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2177),
                            views = 0,
                            year_public = 2010
                        },
                        new
                        {
                            Id = 4,
                            author_id = 30,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2189),
                            description = "Vel reprehenderit similique illo et eos. Quo rerum saepe adipisci eum et esse animi vitae ipsa. Minima optio qui. Et sapiente eveniet non. Omnis adipisci aliquid quia consequatur quia error tempore.",
                            genre_id = 26,
                            name = "Repudiandae non similique omnis voluptate fugit quia veritatis.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2295),
                            views = 0,
                            year_public = 1968
                        },
                        new
                        {
                            Id = 5,
                            author_id = 2,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2305),
                            description = "Aliquid ab ad ut perferendis nihil laboriosam ipsa. Minima et omnis vel eligendi dignissimos ipsa nemo. Odit nesciunt sequi. Autem esse est eos enim tempora earum ut dolorum id. Omnis animi suscipit sit esse.",
                            genre_id = 26,
                            name = "In ad ad doloribus temporibus velit sit est.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2410),
                            views = 0,
                            year_public = 1960
                        },
                        new
                        {
                            Id = 6,
                            author_id = 11,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2421),
                            description = "Amet natus architecto esse nobis. Debitis quam ipsa facere asperiores voluptas. At aut nihil sunt ipsam nemo aut. Delectus suscipit amet incidunt.",
                            genre_id = 12,
                            name = "Iste rem consequatur dignissimos sapiente eius.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2498),
                            views = 0,
                            year_public = 2018
                        },
                        new
                        {
                            Id = 7,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2509),
                            description = "Nostrum aut officia amet. Non facere non doloremque voluptatem. Aperiam ipsam et quis sed quis accusamus.",
                            genre_id = 19,
                            name = "Reiciendis reprehenderit labore.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2567),
                            views = 0,
                            year_public = 1923
                        },
                        new
                        {
                            Id = 8,
                            author_id = 25,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2578),
                            description = "Praesentium nemo dolore libero voluptatem. Aut consequuntur totam facilis laborum corporis totam consequuntur dolore voluptatem. Eaque repellendus iure ut corporis recusandae mollitia recusandae explicabo.",
                            genre_id = 19,
                            name = "Rerum recusandae itaque dolorem temporibus.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2662),
                            views = 0,
                            year_public = 1931
                        },
                        new
                        {
                            Id = 9,
                            author_id = 27,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2672),
                            description = "Voluptates molestiae doloribus. Nostrum sed quae aspernatur tempore nihil natus atque non. Maiores assumenda qui exercitationem molestiae reiciendis delectus ullam quas. Atque impedit fuga consequuntur aut quibusdam. Voluptas blanditiis aliquid placeat suscipit.",
                            genre_id = 31,
                            name = "Quo eum qui nemo reiciendis accusantium.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2775),
                            views = 0,
                            year_public = 1949
                        },
                        new
                        {
                            Id = 10,
                            author_id = 17,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2787),
                            description = "In laudantium qui quo et voluptas aut. Modi culpa consequatur dolor et officiis maiores et repellendus. Qui sit voluptatum debitis. Veniam dolores error incidunt voluptatum officia.",
                            genre_id = 2,
                            name = "Tempora incidunt in eum quod facilis.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2872),
                            views = 0,
                            year_public = 1920
                        },
                        new
                        {
                            Id = 11,
                            author_id = 13,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2882),
                            description = "Est omnis odio. Asperiores ut quae sit corporis dolor iste. Numquam animi fugit dolorem vel est unde. Veritatis sunt veritatis praesentium quaerat ut non.",
                            genre_id = 17,
                            name = "Impedit reprehenderit laborum quis et.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2959),
                            views = 0,
                            year_public = 1919
                        },
                        new
                        {
                            Id = 12,
                            author_id = 26,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(2968),
                            description = "Sequi ea similique ab enim in in. Voluptatem cumque unde minima voluptas. Facere et nostrum sapiente et aut. Animi omnis adipisci et dicta quaerat. Aliquid fuga nulla placeat.",
                            genre_id = 24,
                            name = "Est repudiandae exercitationem natus blanditiis.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3059),
                            views = 0,
                            year_public = 1983
                        },
                        new
                        {
                            Id = 13,
                            author_id = 18,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3069),
                            description = "Quia expedita illo illum totam dolorum ea quo ipsam. Omnis omnis nisi enim et. Sit velit eaque aut earum. Officiis omnis accusantium eos. Nihil dolorem aperiam et.",
                            genre_id = 23,
                            name = "Sapiente iure deleniti iste vitae in accusantium non alias.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3167),
                            views = 0,
                            year_public = 1977
                        },
                        new
                        {
                            Id = 14,
                            author_id = 28,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3177),
                            description = "Molestiae alias ad aut repellat. Repellendus in animi dolorum. In non asperiores nobis ab cum quae aut. Aut totam nihil similique nulla qui cupiditate nostrum aperiam illum. Aperiam aut facere iusto id velit.",
                            genre_id = 21,
                            name = "Modi et in cumque laboriosam eum quae.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3269),
                            views = 0,
                            year_public = 1942
                        },
                        new
                        {
                            Id = 15,
                            author_id = 2,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3279),
                            description = "Maxime et libero fuga et non at qui. Excepturi et magni cum eum quos rerum pariatur architecto. Voluptas aut illum ea saepe expedita. Ea debitis inventore qui.",
                            genre_id = 21,
                            name = "Nostrum ducimus quis.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3356),
                            views = 0,
                            year_public = 1981
                        },
                        new
                        {
                            Id = 16,
                            author_id = 15,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3366),
                            description = "Dolorem est laboriosam praesentium tempora assumenda. Distinctio aut quod asperiores aperiam quasi cupiditate libero. Dolorum nihil sed commodi. Voluptates nam libero quaerat et praesentium culpa. Alias iure neque perspiciatis aut tempora qui.",
                            genre_id = 24,
                            name = "Enim architecto dolor asperiores debitis rem aut culpa atque.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3469),
                            views = 0,
                            year_public = 1924
                        },
                        new
                        {
                            Id = 17,
                            author_id = 10,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3479),
                            description = "Nihil nulla quas ad dolorem velit ipsam eos a. Ullam perferendis non non dolorum a consequuntur repellat. Labore incidunt assumenda consequatur non nisi. Nostrum quos qui. Et ex quia nam et saepe autem. Repellendus officiis aut consequatur et ipsam.",
                            genre_id = 23,
                            name = "Odio quod corporis esse.",
                            quantity = (byte)8,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3590),
                            views = 0,
                            year_public = 1928
                        },
                        new
                        {
                            Id = 18,
                            author_id = 28,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3601),
                            description = "Natus nisi deserunt est tempora sunt culpa. Excepturi nam est eum laborum provident. Excepturi quasi hic sint minima. Sed deleniti officia exercitationem saepe deleniti rerum libero. Vero et labore aut voluptatum deleniti est sit eum. Repellat consectetur perspiciatis.",
                            genre_id = 14,
                            name = "Nulla odit maxime consequatur enim.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3708),
                            views = 0,
                            year_public = 1984
                        },
                        new
                        {
                            Id = 19,
                            author_id = 29,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3718),
                            description = "Molestiae occaecati quisquam sunt a tenetur eos quia numquam porro. Hic a consequuntur inventore sed quia ut eaque doloremque. Deserunt voluptatem aut ea id dolores.",
                            genre_id = 19,
                            name = "Maiores perferendis nisi molestiae assumenda harum doloremque occaecati accusantium.",
                            quantity = (byte)6,
                            rating = (byte)0,
                            remaining = (byte)1,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3797),
                            views = 0,
                            year_public = 1997
                        },
                        new
                        {
                            Id = 20,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3807),
                            description = "Reprehenderit quam ratione ad. Et qui et minima libero qui cum laborum. Voluptas labore consequatur est quia rerum ut. Maiores voluptatem dicta ab et tempora. Cumque atque dolorem.",
                            genre_id = 10,
                            name = "Aut voluptatem inventore minima.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)0,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3897),
                            views = 0,
                            year_public = 1945
                        },
                        new
                        {
                            Id = 21,
                            author_id = 29,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(3908),
                            description = "Consequuntur deserunt laboriosam aut consectetur sit animi similique. Qui expedita tempore et explicabo qui. Dolor a nobis sit. Dolores earum corporis molestiae optio quasi itaque. Sit placeat magni dolores incidunt ducimus. Ex perspiciatis et.",
                            genre_id = 12,
                            name = "Voluptatem ut consequatur atque dolore quo facilis.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4008),
                            views = 0,
                            year_public = 1952
                        },
                        new
                        {
                            Id = 22,
                            author_id = 29,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4017),
                            description = "Minus odio vel harum dolores veritatis sit quas quos voluptatem. Accusamus voluptatem sapiente et saepe ut magnam neque. Est nesciunt voluptates et iusto dignissimos suscipit earum. Accusantium officiis laborum dicta.",
                            genre_id = 25,
                            name = "Harum praesentium excepturi corporis omnis omnis quae in.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4111),
                            views = 0,
                            year_public = 1990
                        },
                        new
                        {
                            Id = 23,
                            author_id = 7,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4123),
                            description = "Voluptates error vel voluptate. Et modi dolor cumque fugiat qui nisi. Autem et distinctio autem officia autem necessitatibus aut.",
                            genre_id = 10,
                            name = "Numquam id non harum doloribus rerum enim necessitatibus.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)3,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4191),
                            views = 0,
                            year_public = 2005
                        },
                        new
                        {
                            Id = 24,
                            author_id = 30,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4201),
                            description = "Nobis provident error. Cum maiores ea veritatis id. Aut cum minus veritatis ex. Qui officia nemo voluptate dignissimos ad laudantium impedit ut.",
                            genre_id = 18,
                            name = "Nihil quo aliquam qui nihil delectus quidem.",
                            quantity = (byte)9,
                            rating = (byte)0,
                            remaining = (byte)4,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4280),
                            views = 0,
                            year_public = 1962
                        },
                        new
                        {
                            Id = 25,
                            author_id = 21,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4291),
                            description = "Amet totam libero non animi eos nihil. Sit repellat recusandae reiciendis voluptas. Soluta est dicta velit iste laudantium minima beatae quibusdam. Aut eos ipsum voluptas amet.",
                            genre_id = 20,
                            name = "Mollitia architecto cumque illum corrupti impedit ut vero.",
                            quantity = (byte)10,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4377),
                            views = 0,
                            year_public = 1929
                        },
                        new
                        {
                            Id = 26,
                            author_id = 20,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4387),
                            description = "Autem suscipit qui rerum ut minima laudantium iste sit nesciunt. Saepe amet autem quaerat laborum perspiciatis est. Adipisci sit earum nam voluptatem molestias sint cupiditate. Sint quia sed commodi et perferendis velit. Eum nostrum pariatur provident magnam. Expedita cumque ipsam aut quis sapiente ducimus ex blanditiis excepturi.",
                            genre_id = 27,
                            name = "Neque officia optio labore consequatur laborum.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)5,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4510),
                            views = 0,
                            year_public = 1906
                        },
                        new
                        {
                            Id = 27,
                            author_id = 21,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4525),
                            description = "Iste aut qui porro consectetur quae voluptas sit. Sunt nemo consequatur aut. Illo neque ipsam iure. Consequatur et tenetur occaecati corrupti ipsum eos vel ea accusantium. Harum corporis eaque suscipit rerum placeat.",
                            genre_id = 1,
                            name = "Natus distinctio qui dolore vel quia nam.",
                            quantity = (byte)5,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4617),
                            views = 0,
                            year_public = 1900
                        },
                        new
                        {
                            Id = 28,
                            author_id = 16,
                            created_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4627),
                            description = "Veniam delectus eius sed illo eum et labore magni incidunt. Natus provident sed voluptatem quae. Animi et quod possimus voluptate. Facilis architecto quia quidem sunt eligendi dolor placeat nam esse.",
                            genre_id = 29,
                            name = "Ad voluptatum expedita quas voluptatem molestiae inventore.",
                            quantity = (byte)7,
                            rating = (byte)0,
                            remaining = (byte)2,
                            updated_at = new DateTime(2024, 11, 12, 9, 56, 39, 468, DateTimeKind.Local).AddTicks(4717),
                            views = 0,
                            year_public = 1935
                        });
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Omnis harum aut minus nemo quas quibusdam.",
                            name = "Jayde"
                        },
                        new
                        {
                            Id = 2,
                            description = "Excepturi explicabo vel sed velit quasi et.",
                            name = "Abraham"
                        },
                        new
                        {
                            Id = 3,
                            description = "Soluta ducimus officia et odit ullam vel quos sint.",
                            name = "Antonetta"
                        },
                        new
                        {
                            Id = 4,
                            description = "Ut cupiditate et aperiam dolor culpa quis veritatis molestiae quia.",
                            name = "Nicholaus"
                        },
                        new
                        {
                            Id = 5,
                            description = "Qui consequuntur dolorem temporibus eligendi molestias dignissimos expedita est nihil.",
                            name = "Hosea"
                        },
                        new
                        {
                            Id = 6,
                            description = "Nostrum cum eaque impedit consequatur minus recusandae sit.",
                            name = "Napoleon"
                        },
                        new
                        {
                            Id = 7,
                            description = "Reprehenderit asperiores voluptatem praesentium ipsum veritatis.",
                            name = "Mabelle"
                        },
                        new
                        {
                            Id = 8,
                            description = "Dolor ut error magni a.",
                            name = "Ewald"
                        },
                        new
                        {
                            Id = 9,
                            description = "Itaque autem voluptate qui iste dolorem nemo.",
                            name = "Hassie"
                        },
                        new
                        {
                            Id = 10,
                            description = "Neque tempore asperiores consequatur rerum aut.",
                            name = "George"
                        },
                        new
                        {
                            Id = 11,
                            description = "Sit aut veritatis eveniet soluta sunt.",
                            name = "Christopher"
                        },
                        new
                        {
                            Id = 12,
                            description = "Consectetur sed qui quas iusto maxime hic quaerat facere architecto.",
                            name = "Brant"
                        },
                        new
                        {
                            Id = 13,
                            description = "Voluptates asperiores blanditiis omnis.",
                            name = "Avis"
                        },
                        new
                        {
                            Id = 14,
                            description = "Amet non excepturi et quod.",
                            name = "Estell"
                        },
                        new
                        {
                            Id = 15,
                            description = "Esse est omnis maiores magnam deserunt.",
                            name = "Aaliyah"
                        },
                        new
                        {
                            Id = 16,
                            description = "At expedita et temporibus et non sequi ducimus.",
                            name = "Paul"
                        },
                        new
                        {
                            Id = 17,
                            description = "Autem saepe voluptatum voluptatem illum quia temporibus adipisci.",
                            name = "Rhoda"
                        },
                        new
                        {
                            Id = 18,
                            description = "Omnis ut voluptas ex consequatur odit quis consequuntur sit ab.",
                            name = "Lenna"
                        },
                        new
                        {
                            Id = 19,
                            description = "Temporibus laborum molestiae quam nihil perspiciatis cupiditate qui.",
                            name = "Porter"
                        },
                        new
                        {
                            Id = 20,
                            description = "Nulla aperiam eos enim.",
                            name = "Lucio"
                        },
                        new
                        {
                            Id = 21,
                            description = "Vitae quos possimus sint tenetur placeat quia earum dolor.",
                            name = "Pauline"
                        },
                        new
                        {
                            Id = 22,
                            description = "Quia ut nobis consequatur ipsum voluptas a libero.",
                            name = "Johann"
                        },
                        new
                        {
                            Id = 23,
                            description = "Omnis qui minus corrupti fugiat aut illo quisquam quo qui.",
                            name = "Jaylon"
                        },
                        new
                        {
                            Id = 24,
                            description = "Ut consequatur expedita doloribus praesentium commodi voluptatem in.",
                            name = "Stella"
                        },
                        new
                        {
                            Id = 25,
                            description = "Dolorum facilis dolorem debitis.",
                            name = "Aracely"
                        },
                        new
                        {
                            Id = 26,
                            description = "Quisquam temporibus unde pariatur ipsum impedit inventore qui perferendis molestiae.",
                            name = "Mabel"
                        },
                        new
                        {
                            Id = 27,
                            description = "Perspiciatis maxime architecto est.",
                            name = "Rosa"
                        },
                        new
                        {
                            Id = 28,
                            description = "Quaerat provident incidunt dolorem quisquam commodi ipsum eaque qui rerum.",
                            name = "Dock"
                        },
                        new
                        {
                            Id = 29,
                            description = "Voluptates a atque cum cupiditate esse non illo.",
                            name = "Margaret"
                        },
                        new
                        {
                            Id = 30,
                            description = "Eveniet et hic quisquam cum accusamus officia rerum.",
                            name = "Destiney"
                        },
                        new
                        {
                            Id = 31,
                            description = "Veritatis autem sed.",
                            name = "Tyra"
                        },
                        new
                        {
                            Id = 32,
                            description = "In dolores incidunt ipsa delectus.",
                            name = "Anderson"
                        });
                });

            modelBuilder.Entity("QLSach.database.models.BookInteraction", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "comment")
                        .WithOne("bookInteraction")
                        .HasForeignKey("QLSach.database.models.BookInteraction", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Comment", "parent")
                        .WithMany("childrents")
                        .HasForeignKey("parent_id");

                    b.Navigation("book");

                    b.Navigation("parent");

                    b.Navigation("user");
                });

            modelBuilder.Entity("QLSach.database.models.Photo", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", "Book")
                        .WithOne("photo")
                        .HasForeignKey("QLSach.database.models.Photo", "book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLSach.database.models.Register", b =>
                {
                    b.HasOne("QLSach.dbContext.models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.HasOne("QLSach.dbContext.models.author", "author")
                        .WithOne("Book")
                        .HasForeignKey("QLSach.dbContext.models.Book", "author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSach.database.models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("author");
                });

            modelBuilder.Entity("QLSach.database.models.Comment", b =>
                {
                    b.Navigation("bookInteraction")
                        .IsRequired();

                    b.Navigation("childrents");
                });

            modelBuilder.Entity("QLSach.database.models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLSach.database.models.User", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("QLSach.dbContext.models.Book", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("photo");
                });

            modelBuilder.Entity("QLSach.dbContext.models.author", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
