services:

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - "8080:80"
        environment:
          PMA_HOST: mysql      # Kết nối tới service MySQL có tên là "mysql"
          PMA_PORT: 3306
        networks:
          - network

    zookeeper:
        image: confluentinc/cp-zookeeper
        container_name: zookeeper
        ports:
          - 2181:2181
        environment:
          - ZOOKEEPER_CLIENT_PORT=2181
          - ZOOKEEPER_TICK_TIME=2000
        networks:
          - kafka

    kafka:
        image: confluentinc/cp-kafka
        container_name: kafka
        ports:
          - 9092:9092
        environment:
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          - KAFKA_BROKER_ID=1
          - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        networks:
          - kafka
        volumes:
          - kafka:/var/lib/kafka/data

networks:
    kafka:
    network:
        driver: bridge
volumes:
    mysql:
        driver: local
    kafka:
        driver: local