services:

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - "8080:80"
        environment:
          PMA_HOST: mysql      # Kết nối tới service MySQL có tên là "mysql"
          PMA_PORT: 3306
        networks:
          - network

networks:
    network:
        driver: bridge
volumes:
    mysql:
        driver: local